/*
 NOTE: This file is an automatically generated file. Any changes made to this file will be lost.*/
window.ICX=window.ICX||{};ICX.client_id="10049";ICX.ra=false;ICX.domain_id=ICX.domain_id||"5961";ICX.lotame_exchange=true;ICX.lotame_exchange_id=4424;ICX.hearst=true;
(function(){var ICX,ICX_LOTAME_EXCHANGE;ICX=window.ICX||{};IC=window.IC||{};ICX.exchange_dependents=ICX.exchange_dependents||[];ICX.lotame_exchange_frequency=ICX.lotame_exchange_frequency||336;ICX_LOTAME_EXCHANGE=window.ICX_LOTAME_EXCHANGE||{};ICX_LOTAME_EXCHANGE.util={addEvent:function(elem,event,fn){if(elem.addEventListener)elem.addEventListener(event,fn,false);else elem.attachEvent("on"+event,function(){return fn.call(elem,window.event)})},readyState:function(){return document.readyState},setAfterExchangeFunc:function(){ICX_LOTAME_EXCHANGE.after_exchange=
ICX_LOTAME_EXCHANGE.after_exchange||function(){}},client_id:function(ICX){ICX.lotame_exchange_id=ICX.lotame_exchange_id||0;return ICX.lotame_exchange_id},build_url:function(icrossingId,ICX){return ICX.util.protocol()+"//bcp.crwdcntrl.net/5/c="+ICX_LOTAME_EXCHANGE.util.client_id(ICX)+"/tp=ICRN/tpid="+icrossingId+"?"+encodeURIComponent("http://cx2.ic-live.com/exchange?exchange_id=2&external_user_id=${profile_id}")},fireImage:function(){var img=new Image;ICX_LOTAME_EXCHANGE.util.addEvent(img,"load",
ICX_LOTAME_EXCHANGE.after_exchange);img.src=ICX_LOTAME_EXCHANGE.util.build_url(ICX_LOTAME_EXCHANGE.icrossingId,ICX_LOTAME_EXCHANGE.ICX)},exchange_fire:function(icrossingId,ICX){if(ICX_LOTAME_EXCHANGE.util.client_id(ICX)===0||ICX.util.cookie.get("icx-lotame-exchange"))return false;ICX_LOTAME_EXCHANGE.icrossingId=icrossingId;ICX_LOTAME_EXCHANGE.ICX=ICX;ICX.util.cookie.set("icx-lotame-exchange",true,-1,ICX.lotame_exchange_frequency);if(ICX_LOTAME_EXCHANGE.util.readyState()==="complete")ICX_LOTAME_EXCHANGE.util.fireImage();
else ICX_LOTAME_EXCHANGE.util.addEvent(window,"load",ICX_LOTAME_EXCHANGE.util.fireImage)}};ICX_LOTAME_EXCHANGE.adddependent=function(){if(!ICX.lotame&&!IC.lotame)ICX.exchange_dependents.push(ICX_LOTAME_EXCHANGE.util.exchange_fire)};window.ICX_LOTAME_EXCHANGE=ICX_LOTAME_EXCHANGE;window.ICX=ICX;ICX_LOTAME_EXCHANGE.util.setAfterExchangeFunc();ICX_LOTAME_EXCHANGE.adddependent()})();
(function(){var ICX,ICX_MEDIA_OS;ICX=window.ICX||{};ICX.exchange_dependents=ICX.exchange_dependents||[];ICX_MEDIA_OS=window.ICX_MEDIA_OS||{};ICX_MEDIA_OS.util={exchange_fire:function(icrossingId,ICX){if(icrossingId!=="")ICX.exchange_cookie_id=icrossingId}};ICX_MEDIA_OS.adddependent=function(){ICX.exchange_dependents.push(ICX_MEDIA_OS.util.exchange_fire)};window.ICX_MEDIA_OS=ICX_MEDIA_OS;window.ICX=ICX;ICX_MEDIA_OS.adddependent()})();
(function(){var baseUrl,defaults,ICX,ICVars,I2A,flr,rnd,pow,ic_version;ic_version="20160830";defaults=function(){var defaults;defaults={pageAction:0,client_id:0,domain_id:0,campaign_id:8,sale:"",price:"",sku:"",order_code:"",currency_id:"",ic_ch:"",altid:"",ic_mid:"",ic_uq:"",event_label:"",event_type:"",event_opt_params:{},refVar:"",ic_url:""};for(var i=1;i<=20;i++)defaults["user_defined"+i]="";return defaults}();flr=Math.floor;rnd=Math.random;pow=Math.pow;ICX=window.ICX||{};ICVars=window.ICVars||
{};I2A=window.I2A||{};IC=window.IC||{};ICX.request_que=[];ICX.exchange_dependents=ICX.exchange_dependents||[];ICX.initial_request=true;ICX.util={cookieEnabled:function(){return window.navigator.cookieEnabled},hostname:function(){return window.location.hostname},location:function(){return window.location.href},protocol:function(){return window.location.protocol},referrer:function(){return document.referrer},isObj:function(obj){return typeof obj==="object"&&typeof obj.length!=="number"},merge:function(target){var a,
sourceProperty,property,source;target=typeof target!=="object"?{}:target;for(a=1;source=arguments[a];a++)for(property in source)if(source.hasOwnProperty(property)){sourceProperty=source[property];if(ICX.util.isObj(sourceProperty)&&ICX.util.isObj(target[property])){target[property]=ICX.util.merge({},target[property],sourceProperty);continue}target[property]=sourceProperty}return target},visibility:function(){var obj={prerender:[],change:[]};if(document.visibilityState!="undefined"){obj.prerender.push("visibilityState");
obj.change.push("visibilitychange")}if(document.webkitVisibilityState!="undefined"){obj.prerender.push("webkitVisibilityState");obj.change.push("webkitvisibilitychange")}if(!obj.prerender.length)return{};return obj}(),checkVisibilty:function(status){var i,prerender=false;if(!ICX.util.visibility.prerender)return prerender;for(i=0;i<ICX.util.visibility.prerender.length;i++)if(document[ICX.util.visibility.prerender[i]]===status){prerender=true;break}return prerender},cookie:{get:function(name){var regex,
match;name=name.replace(/([.*+?\^=!:${}()|\[\]\/\\])/g,"\\$1");regex=new RegExp("(?:^|;)\\s?"+name+"=(.*?)(?:;|$)","i");match=document.cookie.match(regex);return match&&decodeURIComponent(match[1])},set:function(name,value,days,hours){var i,date,params,domains;date=new Date;date.setDate(date.getDate()+(days===-1?"":days||1));date.setHours(date.getHours()+(hours?hours:0));domains=ICX.util.hostname().split(".");for(i=1;i<domains.length+1;i++){params=[];params.push(encodeURIComponent(value));params.push("expires="+
date.toUTCString());params.push("path=/");params.push("domain=."+domains.slice(-i).join("."));document.cookie=name+"="+params.join("; ")}},remove:function(name){ICX.util.cookie.set(name,"",-2)}},uuid:function(){return(new Date).getTime()+"-"+flr(rnd()*pow(2,53))},buildData:function(){var data,key;data={};for(key in defaults)if(defaults.hasOwnProperty(key))if(typeof ICX[key]!=="undefined")data[key]=ICX[key];else if(typeof window[key]!=="undefined")data[key]=window[key];else data[key]=defaults[key];
return data},icxid:function(){var icxid;icxid="nocookie";if(ICX.util.cookieEnabled()){icxid=ICX.util.cookie.get("icxid")||ICX.util.uuid();ICX.util.cookie.set("icxid",icxid,730)}return icxid},Params:function(data){this.start=function(){var params,timeStamp;params=[["cID",data.client_id],["cdid",data.domain_id],["campID",data.campaign_id]];if(ICX.i2a){timeStamp=Math.round((new Date).getTime()/1E3).toString()+(Math.random()*100).toString();params.splice(2,0,["rand",timeStamp])}return params};this.action=
function(){var params,i;params=[["convID",data.pageAction],["convP",data.price],["curID",data.currency_id],["ordID",data.order_code==="*"?"":data.order_code],["ud1",data.user_defined1],["ud2",data.user_defined2],["ud3",data.user_defined3],["ud4",data.user_defined4],["sku",data.sku]];if(!ICX.i2a){for(i=5;i<=20;i++)params.push(["ud"+i,data["user_defined"+i]]);params.push(["sl",data.sale]);if(ICX.ks===true)params.push(["ic_ko_pb","N"])}return params};this.end=function(){var params,i2a,icPixel,i;i2a=
[["altid",data.altid]];icPixel=[["icxid",ICX.icxid],["ic_uq",ICX.ic_uq],["ic_mid",data.ic_mid],["ic_js_ver",ic_version]];if(ICX.initial_request)icPixel=icPixel.concat([["first_hit",1]]);params=[["ic_ch",data.ic_ch],["refVar",data.refVar===""?ICX.util.referrer():data.refVar]];if(!ICX.i2a)if(ICX.hearst)return params.concat(icPixel,[["is_hearst",1]]);else return params.concat(icPixel);else{i2a.unshift(params[0]);i2a.push(params[1]);return i2a}};this.event=function(){var eventAttrs={event_label:data.event_label,
event_type:data.event_type};if(ICX.util.isObj(data.event_opt_params))eventAttrs=ICX.util.merge(eventAttrs,data.event_opt_params);return[["ic_attrs",JSON.stringify(eventAttrs)]]}},addSharedAttrs:function(fullParams){var i,collided,collidedText,key,prefix,sharedAttrs,excludedAttrs;sharedAttrs=[];collided=[];collidedText="collided_";excludedAttrs={state:ICX.initial_request,attrs:["is_media_os"]};for(key in ICX.sharedAttrs)if(ICX.sharedAttrs.hasOwnProperty(key)){prefix="";for(i=0;i<fullParams.length;i++)if(fullParams[i][0]===
key){prefix=collidedText;collided.push([key,ICX.sharedAttrs[key]]);break}if(!ICX.i2a)if(excludedAttrs.state)sharedAttrs.push([prefix+key,ICX.sharedAttrs[key]]);else if(excludedAttrs.attrs.toString().indexOf(key)===-1)sharedAttrs.push([prefix+key,ICX.sharedAttrs[key]])}for(i=0;i<collided.length;i++){delete ICX.sharedAttrs[collided[i][0]];ICX.sharedAttrs[collidedText+collided[i][0]]=collided[i][1]}return sharedAttrs},addAltQueryParams:function(){var params;if(!ICX.altQueryParams)return[];params=[];
for(i=0;i<ICX.altQueryParams.length;i++)params.push([ICX.altQueryParams[i]]);return params},baseUrl:function(data,trackEvent){var baseUrl=(ICX.i2a?"":"p")+data.client_id+".ic-live.com/";if(trackEvent)baseUrl=baseUrl+"generic";else if(ICX.exchange_dependents.length)baseUrl=baseUrl+"hit.js";else if(ICX.i2a)baseUrl=baseUrl+"goat.php";else baseUrl=baseUrl+"favicon.ico";return baseUrl},buildUrl:function(trackEvent){var i,params,data,fullParams,queryParams,url;data=ICX.util.buildData();params=new ICX.util.Params(data);
fullParams=params.start().concat(params.action(),params.end());queryParams=data.pageAction>0&&!trackEvent?fullParams:params.start().concat(params.end());if(!trackEvent){fullParams=fullParams.concat(ICX.util.addAltQueryParams());queryParams=queryParams.concat(ICX.util.addSharedAttrs(fullParams))}if(trackEvent)queryParams=queryParams.concat(params.event());if(!ICX.i2a)queryParams=queryParams.concat([["ic_url",data.ic_url!==""?data.ic_url:ICX.util.location()]]);for(i=0;i<queryParams.length;i++){queryParams[i][1]=
encodeURIComponent(queryParams[i][1]);queryParams[i]=queryParams[i].join("=")}url=ICX.util.protocol()+"//"+ICX.util.baseUrl(data,trackEvent)+"?";return url+queryParams.join("&")},callDependents:function(id){while(ICX.exchange_dependents.length){if(typeof ICX.exchange_dependents[0]==="function")ICX.exchange_dependents[0].call(this,id,ICX);ICX.exchange_dependents.shift()}},fireExchange:function(url){var p,s;p=document.createElement("script");p.type="text/javascript";p.src=url;s=document.getElementsByTagName("script")[0];
s.parentNode.insertBefore(p,s)},queRequest:function(action,type,parameters){if(!action||!type)return false;if(!ICX.util.checkVisibilty("prerender"))if(type==="image")(new Image).src=action;else if(type==="script")ICX.util.fireExchange(action);else{if(type==="function")action.apply(null,parameters)}else ICX.request_que.push([action,type,parameters])},visibilitychange:function(){if(ICX.util.checkVisibilty("visible"))while(ICX.request_que.length){if(ICX.request_que[0][1]==="image")(new Image).src=ICX.request_que[0][0];
else if(ICX.request_que[0][1]==="script")ICX.util.fireExchange(ICX.request_que[0][0]);else if(ICX.request_que[0][1]==="function")ICX.request_que[0][0].apply(null,ICX.request_que[0][2]);ICX.request_que.shift()}},initializeEventListener:function(){var i;if(typeof document.addEventListener!=="undefined")for(i=0;i<ICX.util.visibility.change.length;i++)document.addEventListener(ICX.util.visibility.change[i],ICX.util.visibilitychange,false)}};ICX.icxid=ICX.i2a?"":ICX.util.icxid();ICX.ic_uq=ICX.util.uuid();
if(ICX.util.visibility&&ICX.util.visibility.change)ICX.util.initializeEventListener();ICX.pixel=function(ks){if(ICX.page_view===false)return false;if(!ks)ICX.ic_uq=ICX.util.uuid();var type=ICX.exchange_dependents.length?"script":"image";ICX.util.queRequest(ICX.util.buildUrl(),type);if(ICX.initial_request)ICX.initial_request=false};ICX.mediaOsPixel=function(){ICX.initial_request=true;ICX.pixel()};ICX.pixelEvent=function(pageAction){ICX.ic_uq=ICX.util.uuid();if(typeof pageAction!=="undefined")ICX.pageAction=
pageAction;ICX.util.queRequest(ICX.util.buildUrl(),"image");if(ICX.ks===true)ICX_KS.pixelEvent()};ICX.trackEvent=function(event_label,event_type,event_opt_params){ICX.setTrackUrl(event_label,event_type,event_opt_params);ICX.fireTrackEvent()};ICX.setTrackUrl=function(event_label,event_type,event_opt_params){if(!event_label||!event_type)return false;ICX.ic_uq=ICX.util.uuid();ICX.event_label=event_label;ICX.event_type=event_type;ICX.event_opt_params=ICX.util.isObj(event_opt_params)?event_opt_params:
{};ICX.track_url=ICX.util.buildUrl(true)};ICX.fireTrackEvent=function(exitevent){var ic_attrs;if(ICX.track_url){if(exitevent){ic_attrs=ICX.track_url.match(/ic_attrs=(.*?)(&|$)/)[1];ICX.track_url=ICX.track_url.replace(ic_attrs,ic_attrs.slice(0,-3)+encodeURIComponent(',"exitevent":"'+exitevent+'"')+ic_attrs.slice(-3))}ICX.util.queRequest(ICX.track_url,"image")}ICX.track_url=undefined};window.pixel_conversion=I2A.pixelEvent=ICX.pixelEvent;ICX=ICX.util.merge({},ICVars,IC,I2A,ICX);window.ICX=ICX;if(ICX.i2a)window.I2A=
I2A;if(!ICX.ks&&!ICX.ks===true)ICX.pixel()})();
