var notify_visitors_push=function(c,e,b){return e}(window,notify_visitors_push||{});
notify_visitors_push.manual=function(c,e){var b=c.document;return{jQuery:!1,loadjQuery:function(){if(c.jQuery===e){var d=c.jQuery&&"1.10.2"!==c.jQuery.fn.jquery?!0:!1,a=b.createElement("script");a.src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js";a.onload=a.onreadystatechange=function(){var a=this.readyState;if(!a||"complete"==a||"loaded"==a)try{notify_visitors_push.manual.loadjQueryHandler(d)}catch(k){}};(b.getElementsByTagName("head")[0]||b.documentElement).appendChild(a)}else notify_visitors_push.manual.jQuery=
c.jQuery,notify_visitors_push.manual.launch()},loadjQueryHandler:function(b){b?notify_visitors_push.manual.jQuery=c.jQuery.noConflict(!0):(jQuery=c.jQuery.noConflict(!0),notify_visitors_push.manual.jQuery=jQuery);notify_visitors_push.manual.launch()},launch:function(){notify_visitors_push.utils.browser();notify_visitors_push.utils.error_set=0;notify_visitors_push.data.isChromePush||notify_visitors_push.data.isFirefoxPush?notify_visitors_push.chrome.launch():notify_visitors_push.data.isSafariPush&&
notify_visitors_push.safari.launch()}}}(window);
notify_visitors_push.chrome=function(c,e){var b=c.document;return{launch:function(){if(-1!=b.location.href.indexOf("redirect=prompt"))navigator.permissions.query({name:"notifications"}).then(function(a){"prompt"==a.state?Notification.requestPermission().then(function(a){"granted"===a?notify_visitors_push.utils.error(301):"denied"===a?(notify_visitors_push.data.isFirefox?notify_visitors_push.chrome.stats("mozilla_denied"):notify_visitors_push.chrome.stats("chrome_denied"),notify_visitors_push.utils.error(201)):
"default"!==a||notify_visitors_push.data.isFirefox||(notify_visitors_push.chrome.stats("chrome_closed"),notify_visitors_push.utils.error(202))}):"granted"==a.state?"serviceWorker"in navigator?(navigator.serviceWorker.ready.then(function(a){a.pushManager.getSubscription().then(function(a){a?notify_visitors_push.chrome.sendSubscriptionToServer(a):notify_visitors_push.utils.error(302)})["catch"](function(){notify_visitors_push.utils.error(302)})}),setTimeout(function(){notify_visitors_push.utils.error_set||
notify_visitors_push.utils.error(302)},2E3)):notify_visitors_push.utils.error(302):"denied"==a.state&&notify_visitors_push.utils.error(201)});else if("serviceWorker"in navigator){var d="/service-worker.js";notify_visitors_push.auth.swPath&&(d=notify_visitors_push.auth.swPath);navigator.serviceWorker.register(d).then(notify_visitors_push.chrome.initialiseState())}else console.log("Service workers aren't supported in this browser."),notify_visitors_push.utils.error(101)},initialiseState:function(){"showNotification"in
ServiceWorkerRegistration.prototype?"denied"===Notification.permission?(console.log("The user has blocked notifications."),notify_visitors_push.utils.error(201)):"PushManager"in c?navigator.serviceWorker.ready.then(function(b){b.pushManager.getSubscription().then(function(a){a?notify_visitors_push.chrome.sendSubscriptionToServer(a):notify_visitors_push.chrome.subscribe()})["catch"](function(a){console.log("Error during getSubscription()",a);notify_visitors_push.utils.error(104)})}):(console.log("Push messaging isn't supported."),
notify_visitors_push.utils.error(103)):(console.log("Notifications aren't supported."),notify_visitors_push.utils.error(102))},sendSubscriptionToServer:function(b){if(notify_visitors_push.data.isFirefox)notify_visitors_push.mozilla.sendSubscriptionToServer(b);else if(0!==b.endpoint.indexOf("https://android.googleapis.com/gcm/send"))console.log("This browser isn't currently supported for this demo"),notify_visitors_push.utils.error(105);else{if(b.subscriptionId)var a=b.subscriptionId;else a=b.endpoint.split("/"),
a=a[a.length-1];console.log("server subscription id",a);""!=a&&(notify_visitors_push.data.subscribe={},notify_visitors_push.auth.bid_e&&(notify_visitors_push.data.subscribe.bid_e=notify_visitors_push.auth.bid_e),notify_visitors_push.auth.bid&&(notify_visitors_push.data.subscribe.bid=notify_visitors_push.auth.bid),notify_visitors_push.auth.t&&(notify_visitors_push.data.subscribe.t=notify_visitors_push.auth.t),notify_visitors_push.auth.pageUrl&&(notify_visitors_push.data.subscribe.pageUrl=notify_visitors_push.auth.pageUrl),
notify_visitors_push.auth.userID&&(notify_visitors_push.data.subscribe.userID=notify_visitors_push.auth.userID),notify_visitors_push.data.subscribe.subscriptionId=a,b=JSON.stringify(b),b=JSON.parse(b),b.keys&&(b.keys.p256dh&&(notify_visitors_push.data.subscribe.pkey=b.keys.p256dh),b.keys.auth&&(notify_visitors_push.data.subscribe.authkey=b.keys.auth)),notify_visitors_push.nv_p_jsonp.get(notify_visitors_push.data.urls.chrome_subscribe,notify_visitors_push.data.subscribe,notify_visitors_push.chrome.serverResponse))}},
subscribe:function(){navigator.serviceWorker.ready.then(function(c){c.pushManager.subscribe({userVisibleOnly:!0}).then(function(a){b.getElementById("nvpush_popup_background_loader")&&(b.getElementById("nvpush_popup_background_loader").style.display="block");b.getElementById("pushnotify_message_image")&&(b.getElementById("pushnotify_message_image").style.display="none");return notify_visitors_push.chrome.sendSubscriptionToServer(a)})["catch"](function(a){"denied"===Notification.permission?(console.log("Permission for Notifications was denied"),
notify_visitors_push.data.isFirefox?notify_visitors_push.chrome.stats("mozilla_denied"):notify_visitors_push.chrome.stats("chrome_denied"),notify_visitors_push.utils.error(201)):"default"===Notification.permission&&(console.log("Permission box closed"),notify_visitors_push.data.isFirefox||(notify_visitors_push.chrome.stats("chrome_closed"),notify_visitors_push.utils.error(202)))})})},serverResponse:function(b){b.subscriber&&notify_visitors_push.utils.error(200,b.subscriber)},stats:function(b){notify_visitors_push.utils.close=
1;b&&(notify_visitors_push.data.stats={},notify_visitors_push.auth.bid_e&&(notify_visitors_push.data.stats.bid_e=notify_visitors_push.auth.bid_e),notify_visitors_push.auth.bid&&(notify_visitors_push.data.stats.bid=notify_visitors_push.auth.bid),notify_visitors_push.auth.t&&(notify_visitors_push.data.stats.t=notify_visitors_push.auth.t),notify_visitors_push.data.stats.action=b,notify_visitors_push.nv_p_jsonp.get(notify_visitors_push.data.urls.stats,notify_visitors_push.data.stats,notify_visitors_push.chrome.statsResponse))},
statsResponse:function(b){notify_visitors_push.utils.close=0}}}(window);
notify_visitors_push.mozilla=function(c,e){return{sendSubscriptionToServer:function(b){b.endpoint?(console.log("mozilla endpoint",b.endpoint),notify_visitors_push.data.subscribe={},notify_visitors_push.auth.bid_e&&(notify_visitors_push.data.subscribe.bid_e=notify_visitors_push.auth.bid_e),notify_visitors_push.auth.bid&&(notify_visitors_push.data.subscribe.bid=notify_visitors_push.auth.bid),notify_visitors_push.auth.t&&(notify_visitors_push.data.subscribe.t=notify_visitors_push.auth.t),notify_visitors_push.auth.pageUrl&&
(notify_visitors_push.data.subscribe.pageUrl=notify_visitors_push.auth.pageUrl),notify_visitors_push.auth.userID&&(notify_visitors_push.data.subscribe.userID=notify_visitors_push.auth.userID),notify_visitors_push.data.subscribe.endpoint=b.endpoint,b=JSON.stringify(b),b=JSON.parse(b),b.keys&&(b.keys.p256dh&&(notify_visitors_push.data.subscribe.pkey=b.keys.p256dh),b.keys.auth&&(notify_visitors_push.data.subscribe.authkey=b.keys.auth)),notify_visitors_push.nv_p_jsonp.get(notify_visitors_push.data.urls.mozilla_subscribe,
notify_visitors_push.data.subscribe,notify_visitors_push.mozilla.serverResponse)):(console.log("This browser isn't currently supported for this demo"),notify_visitors_push.utils.error(105))},serverResponse:function(b){b.subscriber&&notify_visitors_push.utils.error(200,b.subscriber)}}}(window);
notify_visitors_push.safari=function(c,e){return{launch:function(){var b=c.safari.pushNotification.permission("web.com.notifyvisitors");"default"===b.permission?notify_visitors_push.safari.requestPermissions():"granted"===b.permission?notify_visitors_push.safari.sendSubscriptionToServer(b.deviceToken):"denied"===b.permission&&(console.log("Permission for Notifications was denied"),notify_visitors_push.utils.error(201))},requestPermissions:function(){c.safari.pushNotification.requestPermission("https://www.nvpush.com/safari/hosted",
"web.com.notifyvisitors",{id:notify_visitors_push.auth.bid},function(b){"granted"===b.permission?notify_visitors_push.safari.sendSubscriptionToServer(b.deviceToken):"denied"===b.permission&&(console.log("Permission for Notifications was denied"),notify_visitors_push.chrome.stats("safari_denied"),notify_visitors_push.utils.error(201))})},sendSubscriptionToServer:function(b){console.log("safari token",b);notify_visitors_push.data.subscribe={};notify_visitors_push.auth.bid_e&&(notify_visitors_push.data.subscribe.bid_e=
notify_visitors_push.auth.bid_e);notify_visitors_push.auth.bid&&(notify_visitors_push.data.subscribe.bid=notify_visitors_push.auth.bid);notify_visitors_push.auth.t&&(notify_visitors_push.data.subscribe.t=notify_visitors_push.auth.t);notify_visitors_push.auth.pageUrl&&(notify_visitors_push.data.subscribe.pageUrl=notify_visitors_push.auth.pageUrl);notify_visitors_push.auth.userID&&(notify_visitors_push.data.subscribe.userID=notify_visitors_push.auth.userID);notify_visitors_push.data.subscribe.subscriptionId=
b;notify_visitors_push.nv_p_jsonp.get(notify_visitors_push.data.urls.safari_subscribe,notify_visitors_push.data.subscribe,notify_visitors_push.safari.serverResponse)},serverResponse:function(b){b.subscriber&&notify_visitors_push.utils.error(200,b.subscriber)}}}(window);
notify_visitors_push.data=function(c,e){var b={},d=("https:"==c.document.location.protocol?"https://":"http://")+"push.notifyvisitors.com/";b.urls={chrome_subscribe:d+"brand/t1/chrome_subscribe",safari_subscribe:d+"brand/t1/safari_subscribe",mozilla_subscribe:d+"brand/t1/mozilla_subscribe",stats:d+"brand/t1/stats"};return b}(window);
notify_visitors_push.utils=function(c,e){var b=c.document,d={};return d={error:function(a,d){notify_visitors_push.utils.error_set=1;console.log("push error "+a);d||(d="");var e=JSON.stringify(["nv_push","subscribe",a,d]),f=b.referrer;c.opener?(c.opener.postMessage(e,f),setInterval(function(){notify_visitors_push.utils.close||self.close()},1E3)):c.parent.postMessage(e,f)},browser:function(){notify_visitors_push.data.isSafari=0;notify_visitors_push.data.isChrome=0;notify_visitors_push.data.isFirefox=
0;notify_visitors_push.data.isIE=0;notify_visitors_push.data.isSafariPush=0;notify_visitors_push.data.isChromePush=0;notify_visitors_push.data.isFirefoxPush=0;var a=c.navigator.userAgent;if(b.documentMode||/Edge/.test(navigator.userAgent))notify_visitors_push.data.isIE=1;else if(/chrome/i.test(a))notify_visitors_push.data.isChrome=1,/Android|webOS/i.test(navigator.userAgent)?(a=a.split("/"),a=a[a.length-2]):(a=a.split(" "),a=a[a.length-2].substr(7)),42<=a.substring(0,2)&&(notify_visitors_push.data.isChromePush=
1);else if(0<a.indexOf("Safari")&&-1==a.indexOf("Chrome"))notify_visitors_push.data.isSafari=1,a=a.substring(0,a.indexOf("Safari")).substring(a.substring(0,a.indexOf("Safari")).lastIndexOf("/")+1),7<=parseInt(a,10)&&(notify_visitors_push.data.isSafariPush=1);else if(/firefox/i.test(a)){notify_visitors_push.data.isFirefox=1;var d=a.indexOf("Firefox");a=a.substring(d+8);a=parseInt(""+a,10);isNaN(a)&&(a=parseInt(navigator.appVersion,10));if(44<=a&&!/Android|webOS/i.test(navigator.userAgent)||48<=a&&
/Android|webOS/i.test(navigator.userAgent))notify_visitors_push.data.isFirefoxPush=1}}}}(window);
notify_visitors_push.nv_p_jsonp=function(c,e){function b(b){var a=d.createElement("script"),c=!1;a.src=b;a.async=!0;a.onload=a.onreadystatechange=function(){c||this.readyState&&"loaded"!==this.readyState&&"complete"!==this.readyState||(c=!0,a.onload=a.onreadystatechange=null,a&&a.parentNode&&a.parentNode.removeChild(a))};g||(g=d.getElementsByTagName("head")[0]);g.appendChild(a)}var d=c.document,a=0,g,k,f;c=this;return{get:function(d,e,g){k=-1!==d.indexOf("?")?"&":"?";e=e||{};for(f in e)e.hasOwnProperty(f)&&
(k+=encodeURIComponent(f)+"="+encodeURIComponent(e[f])+"&");var h="nv_p_json"+ ++a;c[h]=function(a){g(a);try{delete c[h]}catch(l){}c[h]=null};b(d+k+"js_callback="+h);return h}}}(window);void 0!=notify_visitors_push.auth&&notify_mainAction();function notify_mainAction(){notify_visitors_push.manual.loadjQuery()};