(function(g){var window=this;var Zya=function(a,b){return g.Vb(a,b)},d6=function(a){g.Cm(a,"zx",g.Va());
return a},e6=function(a,b,c){g.xa(c)||(c=[String(c)]);
g.Fm(a.g,b,c)},$ya=function(a,b){var c=[];
g.lk(b,function(a){try{var b=g.bD.prototype.o.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.u(b)?g.aD(b)&&c.push(a):c.push(a)},a);
return c},aza=function(a,b){var c=$ya(a,b);
(0,g.G)(c,function(a){g.bD.prototype.remove.call(this,a)},a)},bza=function(){var a=g.uG;
aza(a,a.g.Xd(!0))},cza=function(a,b,c,d){var e=new g.tm(null,void 0);
a&&g.um(e,a);b&&g.vm(e,b);c&&g.wm(e,c);d&&g.xm(e,d);return e},dza=function(a){g.NF[a]&&(a=g.NF[a],(0,g.G)(a,function(a){g.LF[a]&&delete g.LF[a]}),a.length=0)},eza=function(a){var b=g.KF();
if(b)if(b.clear(a),a)dza(a);else for(var c in g.NF)dza(c)},f6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.A=!1;this.capabilities=new window.Set;this.experiments=new window.Set;this.theme="u";new g.nm;this.g=this.o="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",fza(this,a.capabilities||""),gza(this,a.experiments||""),this.o=a.remoteControllerUrl||"",
this.g=a.localChannelEncryptionKey||"")},fza=function(a,b){a.capabilities.clear();
(0,g.Jd)(b.split(","),g.Da(Zya,hza)).forEach(function(b){a.capabilities.add(b)})},gza=function(a,b){a.experiments.clear();
b.split(",").forEach(function(b){a.experiments.add(b)})},g6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},h6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},iza=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},jza=function(a){return new g6(a)},kza=function(a){return g.xa(a)?(0,g.H)(a,jza):[]},i6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},j6=function(a){return g.xa(a)?"["+(0,g.H)(a,i6).join(",")+"]":"null"},k6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},lza=function(a){return(0,g.H)(a,function(a){return{key:a.id,
name:a.name}})},l6=function(a,b){return g.fb(a,function(a){return a||b?!a!=!b?!1:a.id==b.id:!0})},m6=function(a,b){return g.fb(a,function(a){return h6(a,b)})},n6=function(){var a=g.xG("yt-remote-connected-devices")||[];
g.Eb(a);return a},mza=function(a){if(g.lb(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.H)(a,function(a,b){return 0==b?a:a.substring(c.length)})},nza=function(a){g.wG("yt-remote-connected-devices",a,86400)},p6=function(){if(o6)return o6;
var a=g.xG("yt-remote-device-id");a||(a=k6(),g.wG("yt-remote-device-id",a,31536E3));for(var b=n6(),c=1,d=a;g.kb(b,d);)c++,d=a+"#"+c;return o6=d},q6=function(){var a=n6(),b=p6();
g.kb(a,b);g.CG()&&g.Gb(a,b);a=mza(a);if(g.lb(a))try{g.AG.remove("remote_sid","/","youtube.com")}catch(c){}else try{g.BG("remote_sid",a.join(","),-1)}catch(c){}},oza=function(){return g.xG("yt-remote-session-browser-channel")},pza=function(){return g.xG("yt-remote-local-screens")||[]},qza=function(){g.wG("yt-remote-lounge-token-expiration",!0,86400)},rza=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.H)(pza(),function(a){return a.loungeToken}),c=(0,g.H)(a,function(a){return a.loungeToken});
(0,g.bm)(c,function(a){return!g.kb(b,a)})&&qza();
g.wG("yt-remote-local-screens",a,31536E3)},sza=function(a,b){g.wG("yt-remote-session-browser-channel",a);
g.wG("yt-remote-session-screen-id",b);var c=n6(),d=p6();g.kb(c,d)||c.push(d);nza(c);q6()},r6=function(a){a||(g.yG("yt-remote-session-screen-id"),g.yG("yt-remote-session-video-id"));
q6();a=n6();g.sb(a,p6());nza(a)},tza=function(){if(!s6){var a=g.hD();
a&&(s6=new g.WC(a))}return s6?!!s6.get("yt-remote-use-staging-server"):!1},uza=function(){var a=window.document.createElement("a");
g.Xc(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.Za(a)},vza=function(a,b){var c=g.Bd("SCRIPT");
c.id=a;c.onload=function(){b&&(0,window.setTimeout)(b,0)};
c.onreadystatechange=function(){switch(c.readyState){case "loaded":case "complete":c.onload()}};
g.Yc(c,g.ae("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"));var d=window.document.getElementsByTagName("head")[0]||window.document.body;d.insertBefore(c,d.firstChild);return c},wza=function(){var a=uza(),b=window.document.getElementById(a),c=b&&g.$E(b,"loaded");
c||b&&!c||(b=vza(a,function(){g.$E(b,"loaded")||(g.ZE(b,"loaded","true"),g.RF(a),g.XD(g.Da(eza,a),0))}))},xza=function(){var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);
return a?(0,window.parseInt)(a[1],10):0},t6=function(a){return!!window.document.currentScript&&(-1!=window.document.currentScript.src.indexOf("?"+a)||-1!=window.document.currentScript.src.indexOf("&"+a))},yza=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},zza=function(a,b){var c=new window.XMLHttpRequest;
c.onreadystatechange=function(){4==c.readyState&&200==c.status&&b(!0)};
c.onerror=function(){b(!1)};
try{c.open("GET",a,!0),c.send()}catch(d){b(!1)}},x6=function(a){if(a>=Aza.length)u6();
else{var b=Aza[a],c="chrome-extension://"+b+Bza;0<=v6.indexOf(b)?zza(c,function(d){d?(window.chrome.cast=window.chrome.cast||{},window.chrome.cast.extensionId=b,w6(c,u6)):x6(a+1)}):w6(c,function(){x6(a+1)})}},w6=function(a,b,c){var d=window.document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(window.document.head||window.document.documentElement).appendChild(d)},y6=function(a){return 0<=window.navigator.userAgent.indexOf(a)},u6=function(){var a=yza();
a&&a(!1,"No cast extension found")},Dza=function(){if(Cza){var a=2,b=yza(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;w6("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",u6,c)}},Eza=function(){if(y6("CriOS")){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
if(a){Dza();a({command:"cast.sender.init"});return}}if(!window.chrome||y6("Edge"))u6();else if(Dza(),y6("Android")&&y6("Chrome/")&&window.navigator.presentation){a="";var b=xza();55<=b?a="55":50<=b&&(a="50");w6("//www.gstatic.com/eureka/clank"+a+Bza,u6)}else x6(0)},z6=function(a,b,c){g.L.call(this);
this.D=null!=c?(0,g.z)(a,c):a;this.qc=b;this.C=(0,g.z)(this.GH,this);this.g=!1;this.o=0;this.A=this.Aa=null;this.B=[]},A6=function(){},B6=function(a,b,c,d){this.g=a;
this.A=b;this.G=c;this.F=d||1;this.C=45E3;this.B=new g.Jm(this);this.o=new g.pg;this.o.setInterval(250)},Gza=function(a,b,c){a.oj=1;
a.nh=d6(b.clone());a.Hi=c;a.D=!0;Fza(a,null)},C6=function(a,b,c,d,e){a.oj=1;
a.nh=d6(b.clone());a.Hi=null;a.D=c;e&&(a.cC=!1);Fza(a,d)},Fza=function(a,b){a.Uj=(0,g.F)();
D6(a);a.Gh=a.nh.clone();e6(a.Gh,"t",a.F);a.Sl=0;a.Nc=a.g.yq(a.g.Ml()?b:null);0<a.dr&&(a.Ko=new g.Pk((0,g.z)(a.jD,a,a.Nc),a.dr));a.B.U(a.Nc,"readystatechange",a.zS);var c=a.ii?g.bc(a.ii):{};a.Hi?(a.tp="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Nc.send(a.Gh,a.tp,a.Hi,c)):(a.tp="GET",a.cC&&!g.xd&&(c.Connection="close"),a.Nc.send(a.Gh,a.tp,null,c));a.g.rf(1)},Jza=function(a,b,c){for(var d=!0;!a.Sh&&a.Sl<c.length;){var e=Hza(a,c);
if(e==E6){4==b&&(a.oh=4,F6(15),d=!1);break}else if(e==Iza){a.oh=4;F6(16);d=!1;break}else G6(a,e)}4==b&&0==c.length&&(a.oh=1,F6(17),d=!1);a.vf=a.vf&&d;d||(H6(a),I6(a))},Hza=function(a,b){var c=a.Sl,d=b.indexOf("\n",c);
if(-1==d)return E6;c=Number(b.substring(c,d));if((0,window.isNaN)(c))return Iza;d+=1;if(d+c>b.length)return E6;var e=b.substr(d,c);a.Sl=d+c;return e},Lza=function(a,b){a.Uj=(0,g.F)();
D6(a);var c=b?window.location.hostname:"";a.Gh=a.nh.clone();g.Cm(a.Gh,"DOMAIN",c);g.Cm(a.Gh,"t",a.F);try{a.wf=new window.ActiveXObject("htmlfile")}catch(n){H6(a);a.oh=7;F6(22);I6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in J6)k=J6[l];else if(l in Kza)k=J6[l]=Kza[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=
m.toString(16).toUpperCase()}k=J6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}d+="</body></html>";c=g.Zc(g.vc("b/12014412"),d);a.wf.open();a.wf.write(g.Rc(c));a.wf.close();a.wf.parentWindow.m=(0,g.z)(a.ER,a);a.wf.parentWindow.d=(0,g.z)(a.uB,a,!0);a.wf.parentWindow.rpcClose=(0,g.z)(a.uB,a,!1);c=a.wf.createElement("DIV");a.wf.parentWindow.document.body.appendChild(c);d=g.Hc(a.Gh.toString());d=g.Oa(g.Ec(d));d=g.Zc(g.vc("b/12014412"),'<iframe src="'+d+'"></iframe>');c.innerHTML=g.Rc(d);
a.g.rf(1)},D6=function(a){a.Gu=(0,g.F)()+a.C;
Mza(a,a.C)},Mza=function(a,b){if(null!=a.qk)throw Error("WatchDog timer not null");
a.qk=K6((0,g.z)(a.VR,a),b)},L6=function(a){a.qk&&(g.w.clearTimeout(a.qk),a.qk=null)},I6=function(a){a.g.Fx()||a.Sh||a.g.Ao(a)},H6=function(a){L6(a);
g.We(a.Ko);a.Ko=null;a.o.stop();g.Pm(a.B);if(a.Nc){var b=a.Nc;a.Nc=null;b.abort();b.dispose()}a.wf&&(a.wf=null)},G6=function(a,b){try{a.g.nB(a,b),a.g.rf(4)}catch(c){}},Oza=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;Nza(a,b,function(e){e?c(!0):g.w.setTimeout(function(){Oza(a,b,c,d,f)},f)})}},Nza=function(a,b,c){var d=new window.Image;
d.onload=function(){try{M6(d),c(!0)}catch(e){}};
d.onerror=function(){try{M6(d),c(!1)}catch(e){}};
d.onabort=function(){try{M6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{M6(d),c(!1)}catch(e){}};
g.w.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
d.src=a},M6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},Pza=function(a){this.g=a;
this.o=new A6},Qza=function(a){var b=N6(a.g,a.tk,"/mail/images/cleardot.gif");
d6(b);Oza(b.toString(),5E3,(0,g.z)(a.PG,a),3,2E3);a.rf(1)},P6=function(a){var b=a.g.I;
if(null!=b)F6(5),b?(F6(11),O6(a.g,a,!1)):(F6(12),O6(a.g,a,!0));else if(a.oe=new B6(a,void 0,void 0,void 0),a.oe.ii=a.Yq,b=a.g,b=N6(b,b.Ml()?a.Tk:null,a.ar),F6(5),!g.vd||g.rc(10))e6(b,"TYPE","xmlhttp"),C6(a.oe,b,!1,a.Tk,!1);else{e6(b,"TYPE","html");var c=a.oe;a=!!a.Tk;c.oj=3;c.nh=d6(b.clone());Lza(c,a)}},Q6=function(a,b,c){this.g=1;
this.o=[];this.B=[];this.C=new A6;this.G=a||null;this.I=null!=b?b:null;this.D=c||!1},Rza=function(a,b){this.g=a;
this.map=b;this.context=null},Sza=function(a){g.Ye.call(this,"statevent",a)},Tza=function(a,b){g.Ye.call(this,"timingevent",a);
this.size=b},Uza=function(a){g.Ye.call(this,"serverreachability",a)},Xza=function(a){Vza(a);
if(3==a.g){var b=a.Bl++,c=a.wn.clone();g.Cm(c,"SID",a.A);g.Cm(c,"RID",b);g.Cm(c,"TYPE","terminate");R6(a,c);b=new B6(a,a.A,b,void 0);b.oj=2;b.nh=d6(c.clone());(new window.Image).src=b.nh;b.Uj=(0,g.F)();D6(b)}Wza(a)},Yza=function(a){a.nH(1,0);
a.wn=N6(a,null,a.Xq);S6(a)},Vza=function(a){a.bh&&(a.bh.abort(),a.bh=null);
a.kc&&(a.kc.cancel(),a.kc=null);a.vg&&(g.w.clearTimeout(a.vg),a.vg=null);T6(a);a.Nd&&(a.Nd.cancel(),a.Nd=null);a.eh&&(g.w.clearTimeout(a.eh),a.eh=null)},Zza=function(a,b){if(0==a.g)throw Error("Invalid operation: sending map when state is closed");
a.o.push(new Rza(a.GN++,b));2!=a.g&&3!=a.g||S6(a)},S6=function(a){a.Nd||a.eh||(a.eh=K6((0,g.z)(a.sB,a),0),a.gj=0)},aAa=function(a,b){if(1==a.g){if(!b){a.Bl=Math.floor(1E5*Math.random());
var c=a.Bl++,d=new B6(a,"",c,void 0);d.ii=null;var e=U6(a),f=a.wn.clone();g.Cm(f,"RID",c);g.Cm(f,"CVER","1");R6(a,f);Gza(d,f,e);a.Nd=d;a.g=2}}else 3==a.g&&(b?$za(a,b):0==a.o.length||a.Nd||$za(a))},$za=function(a,b){if(b)if(6<a.Uh){a.o=a.B.concat(a.o);
a.B.length=0;var c=a.Bl-1;var d=U6(a)}else c=b.G,d=b.Hi;else c=a.Bl++,d=U6(a);var e=a.wn.clone();g.Cm(e,"SID",a.A);g.Cm(e,"RID",c);g.Cm(e,"AID",a.Cj);R6(a,e);c=new B6(a,a.A,c,a.gj+1);c.ii=null;c.setTimeout(Math.round(1E4)+Math.round(1E4*Math.random()));a.Nd=c;Gza(c,e,d)},R6=function(a,b){if(a.qd){var c=a.qd.hx();
c&&g.Lb(c,function(a,c){g.Cm(b,c,a)})}},U6=function(a){var b=Math.min(a.o.length,1E3),c=["count="+b];
if(6<a.Uh&&0<b){var d=a.o[0].g;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.o[e].g,k=a.o[e].map;f=6>=a.Uh?e:f-d;try{g.Lb(k,function(a,b){c.push("req"+f+"_"+b+"="+(0,window.encodeURIComponent)(a))})}catch(l){c.push("req"+f+"_type="+(0,window.encodeURIComponent)("_badmap"))}}a.B=a.B.concat(a.o.splice(0,b));
return c.join("&")},bAa=function(a){a.kc||a.vg||(a.F=1,a.vg=K6((0,g.z)(a.rB,a),0),a.Xi=0)},V6=function(a){if(a.kc||a.vg||3<=a.Xi)return!1;
a.F++;a.vg=K6((0,g.z)(a.rB,a),cAa(a,a.Xi));a.Xi++;return!0},O6=function(a,b,c){a.sp=c;
a.ff=b.Bg;a.D||Yza(a)},T6=function(a){null!=a.Wh&&(g.w.clearTimeout(a.Wh),a.Wh=null)},cAa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},W6=function(a,b){if(2==b||9==b){var c=null;
a.qd&&(c=null);var d=(0,g.z)(a.tT,a);c||(c=new g.tm("//www.google.com/images/cleardot.gif"),d6(c));Nza(c.toString(),1E4,d)}else F6(2);dAa(a,b)},dAa=function(a,b){a.g=0;
a.qd&&a.qd.hw(b);Wza(a);Vza(a)},Wza=function(a){a.g=0;
a.ff=-1;if(a.qd)if(0==a.B.length&&0==a.o.length)a.qd.lq();else{g.vb(a.B);var b=g.vb(a.o);a.B.length=0;a.o.length=0;a.qd.lq(b)}},N6=function(a,b,c){var d=g.Dm(c);
if(""!=d.o)b&&g.vm(d,b+"."+d.o),g.wm(d,d.C);else{var e=window.location;d=cza(e.protocol,b?b+"."+e.hostname:e.hostname,e.port,c)}a.Gk&&g.Lb(a.Gk,function(a,b){g.Cm(d,b,a)});
g.Cm(d,"VER",a.Uh);R6(a,d);return d},K6=function(a,b){if(!g.za(a))throw Error("Fn must not be null and must be a function");
return g.w.setTimeout(function(){a()},b)},F6=function(a){X6.dispatchEvent(new Sza(X6,a))},eAa=function(){},fAa=function(a,b){this.action=a;
this.params=b||{}},Z6=function(a,b){g.L.call(this);
this.g=new g.Yt(this.A,0,this);g.M(this,this.g);this.o=this.qc=0;if(g.za(a))b&&(a=(0,g.z)(a,b));else if(a&&g.za(a.handleEvent))a=(0,g.z)(a.handleEvent,a);else throw Error("Invalid listener argument");this.B=a;Y6(this)},Y6=function(a){a.g.stop();
a.qc=5E3+2E4*Math.random()},$6=function(a,b,c){this.L=a;
this.D=b;this.A=new g.VC;this.o=new Z6(this.XT,this);this.g=this.Za=null;this.J=!1;this.C=null;this.I="";this.G=this.B=0;this.F=[];this.N=c||!1},gAa=function(a){return{firstTestResults:[""],
secondTestResults:!a.g.sp,sessionId:a.g.A,arrayId:a.g.Cj}},hAa=function(a,b){a.G=b||0;
a.o.stop();a.g&&(3==a.g.g&&aAa(a.g),Xza(a.g));a.G=0},a7=function(a){return!!a.g&&3==a.g.g},iAa=function(a,b){(a.D.loungeIdToken=b)||a.o.stop()},b7=function(a){this.port=this.domain="";
this.g="/api/lounge";this.o=!0;a=a||window.document.location.href;var b=g.Gg(a)||"";b&&(this.port=":"+b);this.domain=g.Fg(a)||"";a=g.Ib;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Ya(a,"10.0")&&(this.o=!1))},c7=function(a,b){var c=a.g;
if(g.u(void 0)?0:a.o)c="https://"+a.domain+a.port+a.g;return g.Pg(c+b,{})},d7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,Hb:g.Da(a.B,d,!0),onError:g.Da(a.A,e),td:g.Da(a.C,e)};c&&(a.Ob=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.mE(b,a)},mAa=function(){var a=jAa;
kAa();e7.push(a);lAa(e7)},f7=function(a,b){kAa();
var c=e7,d=nAa(a,String(b));g.lb(c)?oAa(d):(lAa(c),(0,g.G)(c,function(a){a(d)}))},kAa=function(){e7||(e7=g.x("yt.mdx.remote.debug.handlers_")||[],g.ua("yt.mdx.remote.debug.handlers_",e7,void 0))},oAa=function(a){var b=(g7+1)%50;
g7=b;h7[b]=a;i7||(i7=49==b)},lAa=function(a){var b=h7;
if(b[0]){var c=g7,d=i7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.G)(a,function(a){a(e)})}while(d!=c);
h7=Array(50);g7=-1;i7=!1}},nAa=function(a,b){var c=((0,g.F)()-pAa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},j7=function(a){g.BF.call(this);
this.F=a;this.g=[]},qAa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.g.push(b);return!0},rAa=function(a,b){var c=a.g.length!=b.length;
a.g=(0,g.Jd)(a.g,function(a){return!!l6(b,a)});
for(var d=0,e=b.length;d<e;d++)c=qAa(a,b[d])||c;return c},sAa=function(a,b){var c=a.g.length;
a.g=(0,g.Jd)(a.g,function(a){return!(a||b?!a!=!b?0:a.id==b.id:1)});
return a.g.length<c},k7=function(a,b,c,d){g.BF.call(this);
this.D=a;this.C=b;this.A=c;this.B=d;this.o=0;this.g=null;this.Aa=window.NaN},m7=function(a){j7.call(this,"LocalScreenService");
this.A=a;this.o=window.NaN;l7(this);this.info("Initializing with "+j6(this.g))},tAa=function(a){if(a.g.length){var b=(0,g.H)(a.g,function(a){return a.id}),c=c7(a.A,"/pairing/get_lounge_token_batch");
d7(a.A,c,{screen_ids:b.join(",")},(0,g.z)(a.SH,a),(0,g.z)(a.RH,a))}},l7=function(a){var b=kza(pza());
b=(0,g.Jd)(b,function(a){return!a.uuid});
return rAa(a,b)},n7=function(a,b){rza((0,g.H)(a.g,iza));
b&&qza()},p7=function(a,b){g.BF.call(this);
this.D=b;var c=g.xG("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.D(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.kb(c,l)}this.g=d;this.C=a;this.A=this.B=window.NaN;this.o=null;o7("Initialized with "+g.xg(this.g))},uAa=function(a,b,c){var d=c7(a.C,"/pairing/get_screen_availability");
d7(a.C,d,{lounge_token:b.token},(0,g.z)(function(a){a=a.screens||[];for(var d=0,e=a.length;d<e;++d)if(a[d].loungeToken==b.token){c("online"==a[d].status);return}c(!1)},a),(0,g.z)(function(){c(!1)},a))},q7=function(a,b){a:if(g.Qb(b)!=g.Qb(a.g))var c=!1;
else{c=g.Sb(b);for(var d=0,e=c.length;d<e;++d)if(!a.g[c[d]]){c=!1;break a}c=!0}c||(o7("Updated online screens: "+g.xg(a.g)),a.g=b,a.T("screenChange"));vAa(a)},r7=function(a){(0,window.isNaN)(a.A)||g.ZD(a.A);
a.A=g.XD((0,g.z)(a.Qt,a),0<a.B&&a.B<(0,g.F)()?2E4:1E4)},o7=function(a){f7("OnlineScreenService",a)},wAa=function(a){var b={};
(0,g.G)(a.D(),function(a){a.token?b[a.token]=a.id:this.Zb("Requesting availability of screen w/o lounge token.")});
return b},vAa=function(a){a=g.Sb(g.Mb(a.g,function(a){return a}));
g.Eb(a);a.length?g.wG("yt-remote-online-screen-ids",a.join(","),60):g.yG("yt-remote-online-screen-ids")},s7=function(a){j7.call(this,"ScreenService");
this.D=a;this.o=this.A=null;this.B=[];this.C={};xAa(this)},zAa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.C[b]);var k=a.fe();if(k=(c?m6(k,c):null)||m6(k,b)){k.uuid=b;var l=t7(a,k);uAa(a.o,l,function(a){e(a?l:null)})}else c?yAa(a,c,(0,g.z)(function(a){var f=t7(this,new g6({name:d,
screenId:c,loungeToken:a,dialId:b||""}));uAa(this.o,f,function(a){e(a?f:null)})},a),f):e(null)},AAa=function(a,b){for(var c=0,d=a.g.length;c<d;++c)if(a.g[c].name==b)return a.g[c];
return null},yAa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={Ob:{screen_ids:b},method:"POST",context:a,Hb:function(a,e){var f=e&&e.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.mE(c7(a.D,"/pairing/get_lounge_token_batch"),e)},BAa=function(a){a.g=a.A.fe();
var b=a.C,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.g.length;b<d;++b){var e=a.g[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+j6(a.g))},xAa=function(a){u7(a);
a.A=new m7(a.D);a.A.subscribe("screenChange",(0,g.z)(a.eI,a));BAa(a);a.B=kza(g.xG("yt-remote-automatic-screen-cache")||[]);u7(a);a.info("Initializing automatic screens: "+j6(a.B));a.o=new p7(a.D,(0,g.z)(a.fe,a,!0));a.o.subscribe("screenChange",(0,g.z)(function(){this.T("onlineScreenChange")},a))},t7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=m6(a.B,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.B.push(b),g.wG("yt-remote-automatic-screen-cache",(0,g.H)(a.B,iza)));u7(a);a.C[b.uuid]=b.id;g.wG("yt-remote-device-id-map",a.C,31536E3);return b},u7=function(a){a.C=g.xG("yt-remote-device-id-map")||{}},v7=function(a,b,c){g.BF.call(this);
this.N=c;this.I=a;this.o=b;this.A=null},w7=function(a,b){f7(a.N,b)},x7=function(a,b){v7.call(this,a,b,"CastSession");
this.g=null;this.B=0;this.D=(0,g.z)(this.eU,this);this.C=(0,g.z)(this.fS,this);this.B=g.XD((0,g.z)(function(){CAa(this,null)},this),12E4)},DAa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.xg(void 0));
var b={type:"getMdxSessionStatus"};a.g?a.g.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.y,(0,g.z)(function(){w7(this,"Failed to send message: getMdxSessionStatus.")},a)):w7(a,"Sending yt message without session: "+g.xg(b))},CAa=function(a,b){g.ZD(a.B);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.A||a.A.id!=b){var c=(0,g.z)(a.Bo,a),d=(0,g.z)(a.ke,a);a.yx(b,c,d,5)}}else a.ke(Error("Waiting for session status timed out."))},y7=function(a,b,c){v7.call(this,a,b,"DialSession");
this.B=this.G=null;this.J="";this.O=c;this.C=null;this.F=g.y;this.D=window.NaN;this.L=(0,g.z)(this.hU,this);this.g=g.y},EAa=function(a){a.g=a.I.pD(a.J,a.o.label,a.o.friendlyName,(0,g.z)(function(a){this.g=g.y;
this.Bo(a)},a),(0,g.z)(function(a){this.g=g.y;
this.ke(a)},a))},FAa=function(a){var b={};
b.pairingCode=a.J;b.theme=a.O;if(a.C){var c=a.C.currentTime||0;b.v=a.C.videoId;b.t=c}tza()&&(b.env_useStageMdx=1);return g.Ng(b)},z7=function(a,b){v7.call(this,a,b,"ManualSession");
this.g=g.XD((0,g.z)(this.Dj,this,null),150)},A7=function(a,b,c,d){g.BF.call(this);
this.o=a;this.F=b||"233637DE";this.D=c||"cl";this.G=d||!1;this.g=null;this.C=!1;this.A=[];this.B=(0,g.z)(this.LQ,this)},GAa=function(a,b){return b?g.fb(a.A,function(a){return h6(b,a.label)},a):null},B7=function(a){f7("Controller",a)},jAa=function(a){window.chrome&&window.chrome.cast&&window.chrome.cast.logMessage&&window.chrome.cast.logMessage(a)},C7=function(a){return a.C||!!a.A.length||!!a.g},D7=function(a,b,c){b!=a.g&&(g.We(a.g),(a.g=b)?(c?a.T("yt-remote-cast2-receiver-resumed",b.o):a.T("yt-remote-cast2-receiver-selected",
b.o),b.subscribe("sessionScreen",(0,g.z)(a.pB,a,b)),b.A?a.T("yt-remote-cast2-session-change",b.A):c&&a.g.Dj(null)):a.T("yt-remote-cast2-session-change",null))},HAa=function(a){var b=a.o.oD(),c=a.g&&a.g.o;
a=(0,g.H)(b,function(a){c&&h6(a,c.label)&&(c=null);var b=a.uuid?a.uuid:a.id,d=GAa(this,a);d?(d.label=b,d.friendlyName=a.name):(d=new window.chrome.cast.Receiver(b,a.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM);return d},a);
c&&(c.receiverType!=window.chrome.cast.ReceiverType.CUSTOM&&(c=new window.chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=window.chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},MAa=function(a,b,c,d,e,f,k){IAa()?JAa(b,e,f,k)&&(F7(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?KAa(a,c):(window.__onGCastApiAvailable=function(b,d){b?KAa(a,c):(G7("Failed to load cast API: "+d),H7(!1),F7(!1),g.yG("yt-remote-cast-available"),g.yG("yt-remote-cast-receiver"),LAa(),
c(!1))},d?window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):wza():Eza())):E7("Cannot initialize because not running Chrome")},LAa=function(){E7("dispose");
var a=I7();a&&a.dispose();g.ua("yt.mdx.remote.cloudview.instance_",null,void 0);NAa(!1);g.PF(J7);J7.length=0},K7=function(){return!!g.xG("yt-remote-cast-installed")},OAa=function(){var a=g.xG("yt-remote-cast-receiver");
return a?a.friendlyName:null},PAa=function(){E7("clearCurrentReceiver");
g.yG("yt-remote-cast-receiver")},QAa=function(){return K7()?I7()?I7().getCastSession():(G7("getCastSelector: Cast is not initialized."),null):(G7("getCastSelector: Cast API is not installed!"),null)},M7=function(){K7()?I7()?L7()?(E7("Requesting cast selector."),I7().requestSession()):(E7("Wait for cast API to be ready to request the session."),J7.push(g.OF("yt-remote-cast2-api-ready",M7))):G7("requestCastSelector: Cast is not initialized."):G7("requestCastSelector: Cast API is not installed!")},N7=
function(a,b){L7()?I7().setConnectedScreenStatus(a,b):G7("setConnectedScreenStatus called before ready.")},IAa=function(){var a=0<=g.Ib.search(/ (CrMo|Chrome|CriOS)\//);
return g.kJ||a},RAa=function(a,b){I7().init(a,b)},JAa=function(a,b,c,d){var e=!1;
I7()||(a=new A7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(a){g.wG("yt-remote-cast-available",a);g.SF("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){E7("onReceiverSelected: "+a.friendlyName);
g.wG("yt-remote-cast-receiver",a);g.SF("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){E7("onReceiverResumed: "+a.friendlyName);
g.wG("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){E7("onSessionChange: "+i6(a));
a||g.yG("yt-remote-cast-receiver");g.SF("yt-remote-cast2-session-change",a)}),g.ua("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
E7("cloudview.createSingleton_: "+e);return e},I7=function(){return g.x("yt.mdx.remote.cloudview.instance_")},KAa=function(a,b){H7(!0);
F7(!1);RAa(a,function(a){a?(NAa(!0),g.RF("yt-remote-cast2-api-ready")):(G7("Failed to initialize cast API."),H7(!1),g.yG("yt-remote-cast-available"),g.yG("yt-remote-cast-receiver"),LAa());b(a)})},E7=function(a){f7("cloudview",a)},G7=function(a){f7("cloudview",a)},H7=function(a){E7("setCastInstalled_ "+a);
g.wG("yt-remote-cast-installed",a)},L7=function(){return!!g.x("yt.mdx.remote.cloudview.apiReady_")},NAa=function(a){E7("setApiReady_ "+a);
g.ua("yt.mdx.remote.cloudview.apiReady_",a,void 0)},F7=function(a){g.ua("yt.mdx.remote.cloudview.initializing_",a,void 0)},O7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.g=-1;this.muted=!1;this.audioTrackId=null;this.F=this.G=0;this.o=null;this.hasNext=this.Lf=!1;this.J=this.I=this.A=this.C=0;this.B=window.NaN;this.D=!1;this.reset(a)},P7=function(a){a.audioTrackId=null;
a.o=null;a.g=-1;a.Lf=!1;a.hasNext=!1;a.G=0;a.F=(0,g.F)();a.C=0;a.A=0;a.I=0;a.J=0;a.B=window.NaN;a.D=!1},Q7=function(a){return a.jb()?((0,g.F)()-a.F)/1E3:0},R7=function(a,b){a.G=b;
a.F=(0,g.F)()},S7=function(a){switch(a.g){case 1:case 1081:return((0,g.F)()-a.F)/1E3+a.G;
case -1E3:return 0}return a.G},T7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&P7(a)},U7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.g;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.cc(a.o);b.hasPrevious=a.Lf;b.hasNext=a.hasNext;b.playerTime=a.G;b.playerTimeAt=a.F;b.seekableStart=a.C;b.seekableEnd=a.A;b.duration=a.I;b.loadedTime=a.J;b.liveIngestionTime=a.B;return b},W7=function(a,b){g.BF.call(this);
this.g=0;this.B=a;this.D=[];this.C=new g.lC;this.A=this.o=null;this.I=(0,g.z)(this.pO,this);this.F=(0,g.z)(this.Dl,this);this.G=(0,g.z)(this.oO,this);this.J=(0,g.z)(this.CO,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Mu,this),SAa(this))):c=3;0!=c&&(b?this.Mu(c):g.XD((0,g.z)(function(){this.Mu(c)},this),0));
var d=QAa();d&&V7(this,d);this.subscribe("yt-remote-cast2-session-change",this.J)},X7=function(a){return new O7(a.B.getPlayerContextData())},SAa=function(a){(0,g.G)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.D.push(this.B.subscribe(a,g.Da(this.HQ,a),this))},a)},TAa=function(a){(0,g.G)(a.D,function(a){this.B.unsubscribeByKey(a)},a);
a.D.length=0},Y7=function(a,b){50>a.C.Jc()&&g.nC(a.C,b)},$7=function(a,b,c){var d=X7(a);
R7(d,c);-1E3!=d.g&&(d.g=b);Z7(a,d)},a8=function(a,b,c){a.B.sendMessage(b,c)},Z7=function(a,b){TAa(a);
a.B.setPlayerContextData(U7(b));SAa(a)},V7=function(a,b){a.A&&(a.A.removeUpdateListener(a.I),a.A.removeMediaListener(a.F),a.Dl(null));
a.A=b;a.A&&(f7("CP","Setting cast session: "+a.A.sessionId),a.A.addUpdateListener(a.I),a.A.addMediaListener(a.F),a.A.media.length&&a.Dl(a.A.media[0]))},UAa=function(a){var b=a.o.media,c=a.o.customData;
if(b&&c){var d=X7(a);b.contentId!=d.videoId&&f7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.g=c.playerState;R7(d,a.o.getEstimatedTime());Z7(a,d)}else f7("CP","No cast media video. Ignoring state update.")},b8=function(a,b,c){return(0,g.z)(function(a){this.Zb("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.Zb("Retrying "+b+" using MDx browser channel."),a8(this,b,c))},a)},c8=function(a,b,c){g.BF.call(this);
this.C=window.NaN;this.O=!1;this.J=this.I=this.L=this.N=window.NaN;this.R=[];this.B=this.F=this.A=this.bb=this.g=null;this.na=a;this.R.push(g.mF(window,"beforeunload",(0,g.z)(this.JH,this)));this.o=[];this.bb=new O7;this.Z=b.id;this.g=VAa(this,c);this.g.subscribe("handlerOpened",this.tO,this);this.g.subscribe("handlerClosed",this.qO,this);this.g.subscribe("handlerError",this.rO,this);this.g.subscribe("handlerMessage",this.sO,this);iAa(this.g,b.token);this.subscribe("remoteQueueChange",function(){var a=
this.bb.videoId;g.CG()&&g.wG("yt-remote-session-video-id",a)},this)},d8=function(a){f7("conn",a)},VAa=function(a,b){return new $6(c7(a.na,"/bc"),b)},e8=function(a,b){a.T("proxyStateChange",b)},WAa=function(a){a.C=g.XD((0,g.z)(function(){d8("Connecting timeout");
this.D(1)},a),2E4)},f8=function(a){g.ZD(a.C);
a.C=window.NaN},g8=function(a){g.ZD(a.N);
a.N=window.NaN},XAa=function(a){h8(a);
a.L=g.XD((0,g.z)(function(){i8(this,"getNowPlaying")},a),2E4)},h8=function(a){g.ZD(a.L);
a.L=window.NaN},ZAa=function(a,b){b&&(f8(a),g8(a));
b==(a7(a.g)&&(0,window.isNaN)(a.C))?b&&(e8(a,1),i8(a,"getSubtitlesTrack")):b?(a.X()&&a.bb.reset(),e8(a,1),i8(a,"getNowPlaying"),YAa(a)):a.D(1)},$Aa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.bb.videoId&&(g.Yb(b.params)?a.bb.o=null:a.bb.o=b.params,a.T("remotePlayerChange"))},aBa=function(a,b){var c=b.params.videoId||b.params.video_id,d=(0,window.parseInt)(b.params.currentIndex,10);
a.bb.listId=b.params.listId||a.bb.listId;T7(a.bb,c,d);a.T("remoteQueueChange")},cBa=function(a,b){b.params=b.params||{};
aBa(a,b);bBa(a,b);a.T("autoplayDismissed")},bBa=function(a,b){var c=(0,window.parseInt)(b.params.currentTime||b.params.current_time,10);
R7(a.bb,(0,window.isNaN)(c)?0:c);c=(0,window.parseInt)(b.params.state,10);c=(0,window.isNaN)(c)?-1:c;-1==c&&-1E3==a.bb.g&&(c=-1E3);a.bb.g=c;c=Number(b.params.loadedTime);a.bb.J=(0,window.isNaN)(c)?0:c;c=Number(b.params.duration);a.bb.I=(0,window.isNaN)(c)?0:c;c=a.bb;var d=Number(b.params.liveIngestionTime);c.B=d;c.D=(0,window.isNaN)(d)?!1:!0;c=a.bb;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.C=(0,window.isNaN)(d)?0:d;c.A=(0,window.isNaN)(e)?0:e;1==a.bb.g?XAa(a):h8(a);
a.T("remotePlayerChange")},dBa=function(a,b){if(-1E3!=a.bb.g){var c=1085;
switch((0,window.parseInt)(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.bb.g=c;c=(0,window.parseInt)(b.params.currentTime,10);R7(a.bb,(0,window.isNaN)(c)?0:c);a.T("remotePlayerChange")}},eBa=function(a,b){var c="true"==b.params.muted;
a.bb.volume=(0,window.parseInt)(b.params.volume,10);a.bb.muted=c;a.T("remotePlayerChange")},fBa=function(a,b){a.F=b.params.videoId;
a.T("nowAutoplaying",(0,window.parseInt)(b.params.timeout,10))},gBa=function(a,b){var c="true"==b.params.hasNext;
a.bb.Lf="true"==b.params.hasPrevious;a.bb.hasNext=c;a.T("previousNextChange")},YAa=function(a){g.ZD(a.J);
a.J=g.XD((0,g.z)(a.D,a,1),864E5)},i8=function(a,b,c){c?d8("Sending: action="+b+", params="+g.xg(c)):d8("Sending: action="+b);
a.g.sendMessage(b,c)},j8=function(a){j7.call(this,"ScreenServiceProxy");
this.dd=a;this.o=[];this.o.push(this.dd.$_s("screenChange",(0,g.z)(this.cU,this)));this.o.push(this.dd.$_s("onlineScreenChange",(0,g.z)(this.nQ,this)))},lBa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.RD("MDX_CONFIG")||b;g.uG&&bza();q6();k8||(k8=new b7(b?b.loungeApiHost:void 0),tza()&&(k8.g="/api/loungedev"));l8||(l8=g.x("yt.mdx.remote.deferredProxies_")||[],g.ua("yt.mdx.remote.deferredProxies_",l8,void 0));hBa();var c=m8();if(!c){var d=new s7(k8);g.ua("yt.mdx.remote.screenService_",d,void 0);c=m8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);MAa(a,d,function(a){a?n8()&&N7(n8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){g.SF("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.x("yt.mdx.remote.initialized_")&&(g.ua("yt.mdx.remote.initialized_",!0,void 0),o8("Initializing: "+g.xg(b)),p8.push(g.OF("yt-remote-cast2-availability-change",function(){g.SF("yt-remote-receiver-availability-change")})),p8.push(g.OF("yt-remote-cast2-receiver-selected",function(){q8(null);
g.SF("yt-remote-auto-connect","cast-selector-receiver")})),p8.push(g.OF("yt-remote-cast2-receiver-resumed",function(){g.SF("yt-remote-receiver-resumed","cast-selector-receiver")})),p8.push(g.OF("yt-remote-cast2-session-change",iBa)),p8.push(g.OF("yt-remote-connection-change",function(a){a?N7(n8(),"YouTube TV"):r8()||(N7(null,null),PAa())})),a=s8(),b.isAuto&&(a.id+="#dial"),g.FE("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),o8(" -- with channel params: "+
g.xg(a)),jBa(a),c.start(),n8()||kBa())},nBa=function(){var a=mBa();
K7()&&g.xG("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},mBa=function(){var a=m8().dd.$_gos();
var b=t8();b&&u8()&&(l6(a,b)||a.push(b));return lza(a)},v8=function(){var a=oBa();
!a&&K7()&&OAa()&&(a={key:"cast-selector-receiver",name:OAa()});return a},oBa=function(){var a=mBa(),b=t8();
b||(b=r8());return g.fb(a,function(a){return b&&h6(b,a.key)?!0:!1})},t8=function(){var a=n8();
if(!a)return null;var b=m8().fe();return m6(b,a)},iBa=function(a){o8("remote.onCastSessionChange_: "+i6(a));
if(a){var b=t8();b&&b.id==a.id?N7(b.id,"YouTube TV"):(b&&S8(),T8(a,1))}else u8()&&S8()},S8=function(){L7()?I7().stopSession():G7("stopSession called before API ready.");
var a=u8();a&&(a.disconnect(1),a9(null))},d9=function(){var a=u8();
return!!a&&3!=a.getProxyState()},o8=function(a){f7("remote",a)},m8=function(){if(!e9){var a=g.x("yt.mdx.remote.screenService_");
e9=a?new j8(a):null}return e9},n8=function(){return g.x("yt.mdx.remote.currentScreenId_")},pBa=function(a){g.ua("yt.mdx.remote.currentScreenId_",a,void 0)},qBa=function(){return g.x("yt.mdx.remote.connectData_")},q8=function(a){g.ua("yt.mdx.remote.connectData_",a,void 0)},u8=function(){return g.x("yt.mdx.remote.connection_")},a9=function(a){var b=u8();
q8(null);a||pBa("");g.ua("yt.mdx.remote.connection_",a,void 0);l8&&((0,g.G)(l8,function(b){b(a)}),l8.length=0);
b&&!a?g.SF("yt-remote-connection-change",!1):!b&&a&&g.SF("yt-remote-connection-change",!0)},r8=function(){var a=g.CG();
if(!a)return null;var b=m8().fe();return m6(b,a)},T8=function(a,b){t8()&&t8();
pBa(a.id);var c=new c8(k8,a,s8());c.connect(b,qBa());c.subscribe("beforeDisconnect",function(a){g.SF("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){u8()&&a9(null)});
a9(c)},kBa=function(){var a=r8();
a?(o8("Resume connection to: "+i6(a)),T8(a,0)):(r6(),PAa(),o8("Skipping connecting because no session screen found."))},hBa=function(){var a=s8();
if(g.Yb(a)){a=p6();var b=g.xG("yt-remote-session-name")||"",c=g.xG("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,"mdx-version":3};g.ua("yt.mdx.remote.channelParams_",a,void 0)}},s8=function(){return g.x("yt.mdx.remote.channelParams_")||{}},jBa=function(a){a?(g.wG("yt-remote-session-app",a.app),g.wG("yt-remote-session-name",a.name)):(g.yG("yt-remote-session-app"),g.yG("yt-remote-session-name"));
g.ua("yt.mdx.remote.channelParams_",a,void 0)},f9=function(a,b,c){g.L.call(this);
this.G=a;this.o=b;this.A=new g.yF(this);g.M(this,this.A);this.A.P(b,"onCaptionsTrackListChanged",this.GP);this.A.P(b,"captionschanged",this.nO);this.A.P(b,"captionssettingschanged",this.FC);this.A.P(b,"videoplayerreset",this.Co);this.A.P(b,"mdxautoplaycancel",this.OG);this.R=this.A.P(b,"onVolumeChange",this.ZA);this.F=!1;this.g=c;c.subscribe("proxyStateChange",this.mB,this);c.subscribe("remotePlayerChange",this.Fl,this);c.subscribe("remoteQueueChange",this.Co,this);c.subscribe("autoplayUpNext",this.LA,
this);c.subscribe("previousNextChange",this.jB,this);c.subscribe("nowAutoplaying",this.bB,this);c.subscribe("autoplayDismissed",this.KA,this);this.suggestion=null;this.I=new g.kO(64);this.B=new g.Yt(this.BC,500,this);g.M(this,this.B);this.C=new g.Yt(this.CC,1E3,this);g.M(this,this.C);this.L=new z6(this.CT,0,this);g.M(this,this.L);this.D={};this.N=new g.Yt(this.dD,1E3,this);g.M(this,this.N);this.J=new g.Pk(this.YK,1E3,this);g.M(this,this.J);this.O=g.y;this.FC();this.Co();this.Fl()},g9=function(a,b){var c=
a.G,d=a.o.fa().lengthSeconds;
c.I=b||0;c.g.T("progresssync",b,d)},rBa=function(a){g9(a,0);
a.B.stop();h9(a,new g.kO(64))},j9=function(a,b){if(i9(a)&&!a.F){var c=null;
b&&(c={style:a.o.zi()},g.ec(c,b));a.g.tC(a.o.fa(1).videoId,c);a.D=X7(a.g).o}},k9=function(a,b){var c=a.o.Xf();
if(c){var d=c.ce();var e=c.listId.toString()}var f=a.o.fa(1);c=a.g;var k=f.videoId,l=d;d=f.playerParams;f=f.yj;var m=X7(c),n=e||m.listId;l=l||0;var q={videoId:k,currentIndex:l};T7(m,k,l);g.u(b)&&(R7(m,b),q.currentTime=b);g.u(n)&&(q.listId=n);null!=d&&(q.playerParams=d);null!=f&&(q.clickTrackingParams=f);a8(c,"setPlaylist",q);e||Z7(c,m);h9(a,new g.kO(1))},sBa=function(a,b){if(b){var c=a.o.xc("captions","tracklist",{vy:1});
c&&c.length?(a.o.Fd("captions","track",b),a.F=!1):(a.o.ul("captions"),a.F=!0)}else a.o.Fd("captions","track",{})},i9=function(a){return X7(a.g).videoId==a.o.fa(1).videoId},h9=function(a,b){a.C.stop();
var c=a.I;if(!g.rO(c,b)){var d=g.V(b,2);d!=g.V(a.I,2)&&g.oU(a.o,d);a.I=b;tBa(a.G,c,b)}},l9=function(a){g.Y.call(this,{H:"div",
M:"ytp-remote",K:[{H:"div",M:"ytp-remote-display-status",K:[{H:"div",M:"ytp-remote-display-status-icon",K:[g.kV()]},{H:"div",M:"ytp-remote-display-status-text",K:["{{statustext}}"]}]}]});this.o=new g.JV(this,250);g.M(this,this.o);this.A=a;this.P(a,"presentingplayerstatechange",this.B);uBa(this,g.lU(a))},uBa=function(a,b){if(3==a.A.Qa()){var c={RECEIVER_NAME:a.A.xc("remote","currentReceiver").name};
c=g.V(b,128)?g.T("YTP_MDX_STATUS_ERROR_2",c):b.jb()||g.V(b,4)?g.T("YTP_MDX_STATUS_PLAYING_2",c):g.T("YTP_MDX_STATUS_CONNECTED_2",c);a.updateValue("statustext",c);a.o.show()}else a.o.hide()},m9=function(a,b){g.e_.call(this,g.T("YTP_MDX_TITLE"),0,a,b);
this.o=a;this.G={};this.P(a,"onMdxReceiversChange",this.J);this.P(a,"presentingplayerstatechange",this.J);this.J()},n9=function(a){g.LU.call(this,a);
this.A={key:k6(),name:g.T("YTP_MDX_MY_COMPUTER")};this.C=null;this.D=[];this.J=this.o=null;this.G=[this.A];this.B=this.A;this.F=new g.kO(64);this.I=0;if(!g.SL(g.X(this.g))){a=this.g;var b=g.eU(a).I;b&&(b=b.A&&b.A.g)&&(b=new m9(a,b),g.M(this,b));b=new l9(a);g.M(this,b);g.FU(a,b.element,4)}},tBa=function(a,b,c){a.F=c;
a.g.T("presentingplayerstatechange",new g.xO(c,b))},o9=function(a,b){if(b.key!=a.B.key)if(b.key==a.A.key)S8();
else{a.B=b;var c=a.g.getPlaylistId();var d=a.g.fa(1),e=d.videoId;if(c||e){var f=a.g.Xf();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.fc(l).videoId}else k=[e];f=a.g.getCurrentTime(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.yj,index:Math.max(a.g.Ez(),0),currentTime:0==f?void 0:f}}else c=null;o8("Connecting to: "+g.xg(b));"cast-selector-receiver"==b.key?(q8(c||null),L7()?I7().setLaunchParams(c||null):G7("setLaunchParams called before ready.")):!c&&
d9()&&n8()==b.key?g.SF("yt-remote-connection-change",!0):(S8(),q8(c||null),c=m8().fe(),(c=m6(c,b.key))&&T8(c,1))}},Kza={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},J6={"'":"\\'"},vBa={},hza={LV:"atp",o0:"ska",D_:"que",PZ:"mus",k0:"sus"};
f6.prototype.cn=function(){var a=new f6({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.A=this.A;a.o=this.o;a.g=this.g};
var s6,o6="",Bza=t6("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",Cza=t6("loadCastFramework")||t6("loadCastApplicationFramework"),v6=["boadgeojelhgndaghljhdicfkmllpafd","dliochdbjfkdbacpmhlcpmleaejidimm","enhhojjnijigcajfphajepfemndkmdlo","fmfcbgogabcbclcofgocippekhfcmgfj"],wBa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","fjhoaacokmgbjemoflkofnenfaiekifl"],Aza=50<=xza()?wBa.concat(v6):v6.concat(wBa);g.A(z6,g.L);g.h=z6.prototype;g.h.FH=function(a){this.B=arguments;this.g=!1;this.Aa?this.A=(0,g.F)()+this.qc:this.Aa=g.rg(this.C,this.qc)};
g.h.stop=function(){this.Aa&&(g.sg(this.Aa),this.Aa=null);this.A=null;this.g=!1;this.B=[]};
g.h.pause=function(){++this.o};
g.h.resume=function(){this.o&&(--this.o,!this.o&&this.g&&(this.g=!1,this.D.apply(null,this.B)))};
g.h.W=function(){this.stop();z6.Y.W.call(this)};
g.h.GH=function(){this.A?(this.Aa=g.rg(this.C,this.A-(0,g.F)()),this.A=null):(this.Aa=null,this.o?this.g=!0:(this.g=!1,this.D.apply(null,this.B)))};A6.prototype.stringify=function(a){return g.w.JSON.stringify(a,void 0)};
A6.prototype.parse=function(a){return g.w.JSON.parse(a,void 0)};g.h=B6.prototype;g.h.ii=null;g.h.vf=!1;g.h.qk=null;g.h.Gu=null;g.h.Uj=null;g.h.oj=null;g.h.nh=null;g.h.Gh=null;g.h.Hi=null;g.h.Nc=null;g.h.Sl=0;g.h.wf=null;g.h.tp=null;g.h.oh=null;g.h.Uk=-1;g.h.cC=!0;g.h.Sh=!1;g.h.dr=0;g.h.Ko=null;var Iza={},E6={};g.h=B6.prototype;g.h.setTimeout=function(a){this.C=a};
g.h.zS=function(a){a=a.target;var b=this.Ko;b&&3==g.sx(a)?b.mj():this.jD(a)};
g.h.jD=function(a){try{if(a==this.Nc)a:{var b=g.sx(this.Nc),c=this.Nc.o,d=this.Nc.getStatus();if(g.vd&&!g.rc(10)||g.xd&&!g.qc("420+")){if(4>b)break a}else if(3>b||3==b&&!g.$e&&!g.wx(this.Nc))break a;this.Sh||4!=b||7==c||(8==c||0>=d?this.g.rf(3):this.g.rf(2));L6(this);var e=this.Nc.getStatus();this.Uk=e;var f=g.wx(this.Nc);(this.vf=200==e)?(4==b&&H6(this),this.D?(Jza(this,b,f),g.$e&&this.vf&&3==b&&(this.B.U(this.o,"tick",this.rS),this.o.start())):G6(this,f),this.vf&&!this.Sh&&(4==b?this.g.Ao(this):
(this.vf=!1,D6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.oh=3,F6(13)):(this.oh=0,F6(14)),H6(this),I6(this))}}catch(k){this.Nc&&g.wx(this.Nc)}finally{}};
g.h.rS=function(){var a=g.sx(this.Nc),b=g.wx(this.Nc);this.Sl<b.length&&(L6(this),Jza(this,a,b),this.vf&&4!=a&&D6(this))};
g.h.ER=function(a){K6((0,g.z)(this.DR,this,a),0)};
g.h.DR=function(a){this.Sh||(L6(this),G6(this,a),D6(this))};
g.h.uB=function(a){K6((0,g.z)(this.CR,this,a),0)};
g.h.CR=function(a){this.Sh||(H6(this),this.vf=a,this.g.Ao(this),this.g.rf(4))};
g.h.cancel=function(){this.Sh=!0;H6(this)};
g.h.VR=function(){this.qk=null;var a=(0,g.F)();0<=a-this.Gu?(2!=this.oj&&this.g.rf(3),H6(this),this.oh=2,F6(18),I6(this)):Mza(this,this.Gu-a)};g.h=Pza.prototype;g.h.Yq=null;g.h.oe=null;g.h.Mo=!1;g.h.Gx=null;g.h.tn=null;g.h.Zq=null;g.h.ar=null;g.h.Ke=null;g.h.Bg=-1;g.h.Tk=null;g.h.tk=null;g.h.connect=function(a){this.ar=a;a=N6(this.g,null,this.ar);F6(3);this.Gx=(0,g.F)();var b=this.g.G;null!=b?(this.Tk=b[0],(this.tk=b[1])?(this.Ke=1,Qza(this)):(this.Ke=2,P6(this))):(e6(a,"MODE","init"),this.oe=new B6(this,void 0,void 0,void 0),this.oe.ii=this.Yq,C6(this.oe,a,!1,null,!0),this.Ke=0)};
g.h.PG=function(a){if(a)this.Ke=2,P6(this);else{F6(4);var b=this.g;b.ff=b.bh.Bg;W6(b,9)}a&&this.rf(2)};
g.h.yq=function(a){return this.g.yq(a)};
g.h.abort=function(){this.oe&&(this.oe.cancel(),this.oe=null);this.Bg=-1};
g.h.Fx=function(){return!1};
g.h.nB=function(a,b){this.Bg=a.Uk;if(0==this.Ke)if(b){try{var c=this.o.parse(b)}catch(d){c=this.g;c.ff=this.Bg;W6(c,2);return}this.Tk=c[0];this.tk=c[1]}else c=this.g,c.ff=this.Bg,W6(c,2);else if(2==this.Ke)if(this.Mo)F6(7),this.Zq=(0,g.F)();else if("11111"==b){if(F6(6),this.Mo=!0,this.tn=(0,g.F)(),c=this.tn-this.Gx,!g.vd||g.rc(10)||500>c)this.Bg=200,this.oe.cancel(),F6(12),O6(this.g,this,!0)}else F6(8),this.tn=this.Zq=(0,g.F)(),this.Mo=!1};
g.h.Ao=function(){this.Bg=this.oe.Uk;if(this.oe.vf)0==this.Ke?this.tk?(this.Ke=1,Qza(this)):(this.Ke=2,P6(this)):2==this.Ke&&((!g.vd||g.rc(10)?!this.Mo:200>this.Zq-this.tn)?(F6(11),O6(this.g,this,!1)):(F6(12),O6(this.g,this,!0)));else{0==this.Ke?F6(9):2==this.Ke&&F6(10);var a=this.g;a.ff=this.Bg;W6(a,2)}};
g.h.Ml=function(){return this.g.Ml()};
g.h.isActive=function(){return this.g.isActive()};
g.h.rf=function(a){this.g.rf(a)};g.h=Q6.prototype;g.h.Gk=null;g.h.Nd=null;g.h.kc=null;g.h.Xq=null;g.h.wn=null;g.h.Wv=null;g.h.Ln=null;g.h.Bl=0;g.h.GN=0;g.h.qd=null;g.h.eh=null;g.h.vg=null;g.h.Wh=null;g.h.bh=null;g.h.sp=null;g.h.Cj=-1;g.h.Fy=-1;g.h.ff=-1;g.h.gj=0;g.h.Xi=0;g.h.Uh=8;var X6=new g.zf;g.A(Sza,g.Ye);g.A(Tza,g.Ye);g.A(Uza,g.Ye);g.h=Q6.prototype;g.h.connect=function(a,b,c,d,e){F6(0);this.Xq=b;this.Gk=c||{};d&&g.u(e)&&(this.Gk.OSID=d,this.Gk.OAID=e);this.D?(K6((0,g.z)(this.xw,this,a),100),Yza(this)):this.xw(a)};
g.h.xw=function(a){this.bh=new Pza(this);this.bh.Yq=null;this.bh.o=this.C;this.bh.connect(a)};
g.h.Fx=function(){return 0==this.g};
g.h.sB=function(a){this.eh=null;aAa(this,a)};
g.h.rB=function(){this.vg=null;this.kc=new B6(this,this.A,"rpc",this.F);this.kc.ii=null;this.kc.dr=0;var a=this.Wv.clone();g.Cm(a,"RID","rpc");g.Cm(a,"SID",this.A);g.Cm(a,"CI",this.sp?"0":"1");g.Cm(a,"AID",this.Cj);R6(this,a);if(!g.vd||g.rc(10))g.Cm(a,"TYPE","xmlhttp"),C6(this.kc,a,!0,this.Ln,!1);else{g.Cm(a,"TYPE","html");var b=this.kc,c=!!this.Ln;b.oj=3;b.nh=d6(a.clone());Lza(b,c)}};
g.h.nB=function(a,b){if(0!=this.g&&(this.kc==a||this.Nd==a))if(this.ff=a.Uk,this.Nd==a&&3==this.g)if(7<this.Uh){try{var c=this.C.parse(b)}catch(f){c=null}if(g.xa(c)&&3==c.length)if(0==c[0])a:{if(!this.vg){if(this.kc)if(this.kc.Uj+3E3<this.Nd.Uj)T6(this),this.kc.cancel(),this.kc=null;else break a;V6(this);F6(19)}}else this.Fy=c[1],0<this.Fy-this.Cj&&37500>c[2]&&this.sp&&0==this.Xi&&!this.Wh&&(this.Wh=K6((0,g.z)(this.iO,this),6E3));else W6(this,11)}else b!=vBa.PW.g&&W6(this,11);else if(this.kc==a&&
T6(this),!g.C(b)){c=this.C.parse(b);g.xa(c);for(var d=0;d<c.length;d++){var e=c[d];this.Cj=e[0];e=e[1];2==this.g?"c"==e[0]?(this.A=e[1],this.Ln=e[2],e=e[3],null!=e?this.Uh=e:this.Uh=6,this.g=3,this.qd&&this.qd.jw(),this.Wv=N6(this,this.Ml()?this.Ln:null,this.Xq),bAa(this)):"stop"==e[0]&&W6(this,7):3==this.g&&("stop"==e[0]?W6(this,7):"noop"!=e[0]&&this.qd&&this.qd.iw(e),this.Xi=0)}}};
g.h.iO=function(){null!=this.Wh&&(this.Wh=null,this.kc.cancel(),this.kc=null,V6(this),F6(20))};
g.h.Ao=function(a){if(this.kc==a){T6(this);this.kc=null;var b=2}else if(this.Nd==a)this.Nd=null,b=1;else return;this.ff=a.Uk;if(0!=this.g)if(a.vf)1==b?(b=(0,g.F)()-a.Uj,X6.dispatchEvent(new Tza(X6,a.Hi?a.Hi.length:0,b,this.gj)),S6(this),this.B.length=0):bAa(this);else{var c=a.oh,d;if(!(d=3==c||7==c||0==c&&0<this.ff)){if(d=1==b)this.Nd||this.eh||1==this.g||2<=this.gj?d=!1:(this.eh=K6((0,g.z)(this.sB,this,a),cAa(this,this.gj)),this.gj++,d=!0);d=!(d||2==b&&V6(this))}if(d)switch(c){case 1:W6(this,5);
break;case 4:W6(this,10);break;case 3:W6(this,6);break;case 7:W6(this,12);break;default:W6(this,2)}}};
g.h.nH=function(a){if(!g.kb(arguments,this.g))throw Error("Unexpected channel state: "+this.g);};
g.h.tT=function(a){a?F6(2):(F6(1),dAa(this,8))};
g.h.yq=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new g.mx;a.G=!1;return a};
g.h.isActive=function(){return!!this.qd&&this.qd.isActive(this)};
g.h.rf=function(a){X6.dispatchEvent(new Uza(X6,a))};
g.h.Ml=function(){return!(!g.vd||g.rc(10))};
g.h=eAa.prototype;g.h.jw=function(){};
g.h.iw=function(){};
g.h.hw=function(){};
g.h.lq=function(){};
g.h.hx=function(){return{}};
g.h.isActive=function(){return!0};g.A(Z6,g.L);Z6.prototype.A=function(){500<this.qc&&24E4>2*this.qc&&(this.qc*=2);this.B();this.o&&this.start()};
Z6.prototype.start=function(){g.Zt(this.g,this.qc);this.o=(0,g.F)()+this.qc};
Z6.prototype.stop=function(){this.g.stop();this.o=0};
Z6.prototype.isActive=function(){return this.g.isActive()};g.A($6,eAa);g.h=$6.prototype;g.h.subscribe=function(a,b,c){return this.A.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.A.unsubscribe(a,b,c)};
g.h.Hd=function(a){return this.A.Hd(a)};
g.h.T=function(a,b){return this.A.T.apply(this.A,arguments)};
g.h.dispose=function(){this.J||(this.J=!0,g.We(this.A),hAa(this),g.We(this.o),this.o=null)};
g.h.ia=function(){return this.J};
g.h.connect=function(a,b,c){if(!this.g||2!=this.g.g){this.I="";this.o.stop();this.C=a||null;this.B=b||0;a=this.L+"/test";b=this.L+"/bind";var d=new Q6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.N),e=this.g;e&&(e.qd=null);d.qd=this;this.g=d;e?this.g.connect(a,b,this.D,e.A,e.Cj):c?this.g.connect(a,b,this.D,c.sessionId,c.arrayId):this.g.connect(a,b,this.D)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.ec(c,b);this.o.isActive()||2==(this.g?this.g.g:0)?this.F.push(c):a7(this)&&Zza(this.g,c)};
g.h.jw=function(){Y6(this.o);this.C=null;this.B=0;if(this.F.length){var a=this.F;this.F=[];for(var b=0,c=a.length;b<c;++b)Zza(this.g,a[b])}this.T("handlerOpened")};
g.h.hw=function(a){var b=2==a&&401==this.g.ff;if(4!=a&&!b){if(6==a||410==this.g.ff)b=this.o,b.g.stop(),b.qc=500;this.o.start()}this.T("handlerError",a)};
g.h.lq=function(a){if(!this.o.isActive())this.T("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.F.push(d)}};
g.h.hx=function(){var a={v:2};this.I&&(a.gsessionid=this.I);0!=this.B&&(a.ui=""+this.B);0!=this.G&&(a.ui=""+this.G);this.C&&g.ec(a,this.C);return a};
g.h.iw=function(a){"S"==a[0]?this.I=a[1]:"gracefulReconnect"==a[0]?(Y6(this.o),this.o.start(),Xza(this.g)):this.T("handlerMessage",new fAa(a[0],a[1]))};
g.h.XT=function(){this.o.isActive();var a=this.g,b=0;a.kc&&b++;a.Nd&&b++;0!=b?this.o.start():this.connect(this.C,this.B)};b7.prototype.B=function(a,b,c,d){b?a(d):a({text:c.responseText})};
b7.prototype.A=function(a,b){a(Error("Request error: "+b.status))};
b7.prototype.C=function(a){a(Error("request timed out"))};var pAa=(0,g.F)(),e7=null,h7=Array(50),g7=-1,i7=!1;g.A(j7,g.BF);j7.prototype.fe=function(){return this.g};
j7.prototype.contains=function(a){return!!l6(this.g,a)};
j7.prototype.get=function(a){return a?m6(this.g,a):null};
j7.prototype.info=function(a){f7(this.F,a)};g.A(k7,g.BF);var xBa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=k7.prototype;g.h.start=function(){!this.g&&(0,window.isNaN)(this.Aa)&&this.nD()};
g.h.stop=function(){this.g&&(this.g.abort(),this.g=null);(0,window.isNaN)(this.Aa)||(g.ZD(this.Aa),this.Aa=window.NaN)};
g.h.W=function(){this.stop();k7.Y.W.call(this)};
g.h.nD=function(){this.Aa=window.NaN;this.g=g.mE(c7(this.D,"/pairing/get_screen"),{method:"POST",Ob:{pairing_code:this.C},timeout:5E3,Hb:(0,g.z)(this.aU,this),onError:(0,g.z)(this.ZT,this),td:(0,g.z)(this.bU,this)})};
g.h.aU=function(a,b){this.g=null;var c=b.screen||{};c.dialId=this.A;c.name=this.B;this.T("pairingComplete",new g6(c))};
g.h.ZT=function(a){this.g=null;a.status&&404==a.status?this.o>=xBa.length?this.T("pairingFailed",Error("DIAL polling timed out")):(a=xBa[this.o],this.Aa=g.XD((0,g.z)(this.nD,this),a),this.o++):this.T("pairingFailed",Error("Server error "+a.status))};
g.h.bU=function(){this.g=null;this.T("pairingFailed",Error("Server not responding"))};g.A(m7,j7);g.h=m7.prototype;g.h.start=function(){l7(this)&&this.T("screenChange");!g.xG("yt-remote-lounge-token-expiration")&&tAa(this);g.ZD(this.o);this.o=g.XD((0,g.z)(this.start,this),1E4)};
g.h.add=function(a,b){l7(this);qAa(this,a);n7(this,!1);this.T("screenChange");b(a);a.token||tAa(this)};
g.h.remove=function(a,b){var c=l7(this);sAa(this,a)&&(n7(this,!1),c=!0);b(a);c&&this.T("screenChange")};
g.h.np=function(a,b,c,d){var e=l7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,n7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.T("screenChange")};
g.h.W=function(){g.ZD(this.o);m7.Y.W.call(this)};
g.h.SH=function(a){l7(this);var b=this.g.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}n7(this,!b);b&&f7(this.F,"Missed "+b+" lounge tokens.")};
g.h.RH=function(a){f7(this.F,"Requesting lounge tokens failed: "+a)};g.A(p7,g.BF);g.h=p7.prototype;g.h.start=function(){var a=(0,window.parseInt)(g.xG("yt-remote-fast-check-period")||"0",10);(this.B=(0,g.F)()-144E5<a?0:a)?r7(this):(this.B=(0,g.F)()+3E5,g.wG("yt-remote-fast-check-period",this.B),this.Qt())};
g.h.isEmpty=function(){return g.Yb(this.g)};
g.h.update=function(){o7("Updating availability on schedule.");var a=this.D(),b=g.Mb(this.g,function(b,d){return b&&!!m6(a,d)},this);
q7(this,b)};
g.h.W=function(){g.ZD(this.A);this.A=window.NaN;this.o&&(this.o.abort(),this.o=null);p7.Y.W.call(this)};
g.h.Qt=function(){g.ZD(this.A);this.A=window.NaN;this.o&&this.o.abort();var a=wAa(this);if(g.Qb(a)){var b=c7(this.C,"/pairing/get_screen_availability");this.o=d7(this.C,b,{lounge_token:g.Sb(a).join(",")},(0,g.z)(this.eR,this,a),(0,g.z)(this.dR,this))}else q7(this,{}),r7(this)};
g.h.eR=function(a,b){this.o=null;var c=g.Sb(wAa(this));if(g.Fb(c,g.Sb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;q7(this,d);r7(this)}else this.Zb("Changing Screen set during request."),this.Qt()};
g.h.dR=function(a){this.Zb("Screen availability failed: "+a);this.o=null;r7(this)};
g.h.Zb=function(a){f7("OnlineScreenService",a)};g.A(s7,j7);g.h=s7.prototype;g.h.start=function(){this.A.start();this.o.start();this.g.length&&(this.T("screenChange"),this.o.isEmpty()||this.T("onlineScreenChange"))};
g.h.add=function(a,b,c){this.A.add(a,b,c)};
g.h.remove=function(a,b,c){this.A.remove(a,b,c);this.o.update()};
g.h.np=function(a,b,c,d){this.A.contains(a)?this.A.np(a,b,c,d):(a="Updating name of unknown screen: "+a.name,f7(this.F,a),d(Error(a)))};
g.h.fe=function(a){return a?this.g:g.ub(this.g,(0,g.Jd)(this.B,function(a){return!this.contains(a)},this))};
g.h.oD=function(){return(0,g.Jd)(this.fe(!0),function(a){return!!this.o.g[a.id]},this)};
g.h.pD=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new k7(this.D,a,b,c);f.subscribe("pairingComplete",(0,g.z)(function(a){g.We(f);d(t7(this,a))},this));
f.subscribe("pairingFailed",function(a){g.We(f);e(a)});
f.start();return(0,g.z)(f.stop,f)};
g.h.dU=function(a,b,c,d){g.mE(c7(this.D,"/pairing/get_screen"),{method:"POST",Ob:{pairing_code:a},timeout:5E3,Hb:(0,g.z)(function(a,d){var e=new g6(d.screen||{});if(!e.name||AAa(this,e.name)){a:{var f=e.name;for(var m=2,n=b(f,m);AAa(this,n);){m++;if(20<m)break a;n=b(f,m)}f=n}e.name=f}c(t7(this,e))},this),
onError:(0,g.z)(function(a){d(Error("pairing request failed: "+a.status))},this),
td:(0,g.z)(function(){d(Error("pairing request timed out."))},this)})};
g.h.W=function(){g.We(this.A);g.We(this.o);s7.Y.W.call(this)};
g.h.eI=function(){BAa(this);this.T("screenChange");this.o.update()};
s7.prototype.dispose=s7.prototype.dispose;g.A(v7,g.BF);g.h=v7.prototype;g.h.Bo=function(a){this.A=a;this.T("sessionScreen",this.A)};
g.h.ke=function(a){this.ia()||(a&&w7(this,""+a),this.A=null,this.T("sessionScreen",null))};
g.h.info=function(a){f7(this.N,a)};
g.h.rD=function(){return null};
g.h.Xt=function(a){var b=this.o;a?(b.displayStatus=new window.chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;window.chrome.cast.setReceiverDisplayStatus(b,(0,g.z)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.z)(function(){w7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.W=function(){this.Xt("");v7.Y.W.call(this)};g.A(x7,v7);g.h=x7.prototype;g.h.Wt=function(a){if(this.g){if(this.g==a)return;w7(this,"Overriding cast sesison with new session object");this.g.removeUpdateListener(this.D);this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.C)}this.g=a;this.g.addUpdateListener(this.D);this.g.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.C);DAa(this)};
g.h.Dj=function(a){this.info("launchWithParams no-op for Cast: "+g.xg(a))};
g.h.stop=function(){this.g?this.g.stop((0,g.z)(function(){this.ke()},this),(0,g.z)(function(){this.ke(Error("Failed to stop receiver app."))},this)):this.ke(Error("Stopping cast device witout session."))};
g.h.Xt=g.y;g.h.W=function(){this.info("disposeInternal");g.ZD(this.B);this.B=0;this.g&&(this.g.removeUpdateListener(this.D),this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.C));this.g=null;x7.Y.W.call(this)};
g.h.fS=function(a,b){if(!this.ia())if(b){var c=g.gx(b);if(c){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.xg(c));switch(d){case "mdxSessionStatus":CAa(this,c.screenId);break;default:w7(this,"Unknown youtube message: "+d)}}else w7(this,"Unable to parse message.")}else w7(this,"No data in message.")};
g.h.yx=function(a,b,c,d){zAa(this.I,this.o.label,a,this.o.friendlyName,(0,g.z)(function(e){e?b(e):0<=d?(w7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.XD((0,g.z)(this.yx,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.rD=function(){return this.g};
g.h.eU=function(a){this.ia()||a||(w7(this,"Cast session died."),this.ke())};g.A(y7,v7);g.h=y7.prototype;g.h.Wt=function(a){this.B=a;this.B.addUpdateListener(this.L)};
g.h.Dj=function(a){this.C=a;this.F()};
g.h.stop=function(){this.g();this.g=g.y;g.ZD(this.D);this.B?this.B.stop((0,g.z)(this.ke,this,null),(0,g.z)(this.ke,this,"Failed to stop DIAL device.")):this.ke()};
g.h.W=function(){this.g();this.g=g.y;g.ZD(this.D);this.B&&this.B.removeUpdateListener(this.L);this.B=null;y7.Y.W.call(this)};
g.h.hU=function(a){this.ia()||a||(w7(this,"DIAL session died."),this.g(),this.g=g.y,this.ke())};
g.h.Nr=function(a){this.J=k6();if(this.C){var b=new window.chrome.cast.DialLaunchResponse(!0,FAa(this));a(b);EAa(this)}else this.F=(0,g.z)(function(){g.ZD(this.D);this.F=g.y;this.D=window.NaN;var b=new window.chrome.cast.DialLaunchResponse(!0,FAa(this));a(b);EAa(this)},this),this.D=g.XD((0,g.z)(function(){this.F()},this),100)};
g.h.vJ=function(a,b,c){zAa(this.I,this.G.receiver.label,a,this.o.friendlyName,(0,g.z)(function(a){a&&a.token?(this.Bo(a),b(new window.chrome.cast.DialLaunchResponse(!1))):this.Nr(b,c)},this),(0,g.z)(function(a){w7(this,"Failed to get DIAL screen: "+a);
this.Nr(b,c)},this))};g.A(z7,v7);z7.prototype.stop=function(){this.ke()};
z7.prototype.Wt=g.y;z7.prototype.Dj=function(){g.ZD(this.g);this.g=window.NaN;var a=m6(this.I.fe(),this.o.label);a?this.Bo(a):this.ke(Error("No such screen"))};
z7.prototype.W=function(){g.ZD(this.g);this.g=window.NaN;z7.Y.W.call(this)};g.A(A7,g.BF);g.h=A7.prototype;
g.h.init=function(a,b){window.chrome.cast.timeout.requestSession=3E4;var c=new window.chrome.cast.SessionRequest(this.F);this.G||(c.dialRequest=new window.chrome.cast.DialRequest("YouTube"));var d=window.chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?window.chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:window.chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new window.chrome.cast.ApiConfig(c,(0,g.z)(this.oB,this),(0,g.z)(this.PQ,this),d,e);c.customDialLaunchCallback=(0,g.z)(this.TO,this);window.chrome.cast.initialize(c,
(0,g.z)(function(){this.ia()||(window.chrome.cast.addReceiverActionListener(this.B),mAa(),this.o.subscribe("onlineScreenChange",(0,g.z)(this.qD,this)),this.A=HAa(this),window.chrome.cast.setCustomReceivers(this.A,g.y,(0,g.z)(function(a){this.Zb("Failed to set initial custom receivers: "+g.xg(a))},this)),this.T("yt-remote-cast2-availability-change",C7(this)),b(!0))},this),(0,g.z)(function(a){this.Zb("Failed to initialize API: "+g.xg(a));
b(!1)},this))};
g.h.cT=function(a,b){B7("Setting connected screen ID: "+a+" -> "+b);if(this.g){var c=this.g.A;if(!a||c&&c.id!=a)B7("Unsetting old screen status: "+this.g.o.friendlyName),D7(this,null)}if(a&&b){if(!this.g){c=m6(this.o.fe(),a);if(!c){B7("setConnectedScreenStatus: Unknown screen.");return}var d=GAa(this,c);d||(B7("setConnectedScreenStatus: Connected receiver not custom..."),d=new window.chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM,this.A.push(d),
window.chrome.cast.setCustomReceivers(this.A,g.y,(0,g.z)(function(a){this.Zb("Failed to set initial custom receivers: "+g.xg(a))},this)));
B7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);D7(this,new z7(this.o,d),!0)}this.g.Xt(b)}else B7("setConnectedScreenStatus: no screen.")};
g.h.dT=function(a){this.ia()?this.Zb("Setting connection data on disposed cast v2"):this.g?this.g.Dj(a):this.Zb("Setting connection data without a session")};
g.h.gU=function(){this.ia()?this.Zb("Stopping session on disposed cast v2"):this.g?(this.g.stop(),D7(this,null)):B7("Stopping non-existing session")};
g.h.requestSession=function(){window.chrome.cast.requestSession((0,g.z)(this.oB,this),(0,g.z)(this.iR,this))};
g.h.W=function(){this.o.unsubscribe("onlineScreenChange",(0,g.z)(this.qD,this));window.chrome&&window.chrome.cast&&window.chrome.cast.removeReceiverActionListener(this.B);g.sb(g.x("yt.mdx.remote.debug.handlers_")||[],jAa);g.We(this.g);A7.Y.W.call(this)};
g.h.Zb=function(a){f7("Controller",a)};
g.h.pB=function(a,b){this.g==a&&(b||D7(this,null),this.T("yt-remote-cast2-session-change",b))};
g.h.LQ=function(a,b){if(!this.ia())if(a)switch(a.friendlyName=window.chrome.cast.unescape(a.friendlyName),B7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case window.chrome.cast.ReceiverAction.CAST:if(this.g)if(this.g.o.label!=a.label)B7("onReceiverAction_: Stopping active receiver: "+this.g.o.friendlyName),this.g.stop();else{B7("onReceiverAction_: Casting to active receiver.");this.g.A&&this.T("yt-remote-cast2-session-change",this.g.A);break}switch(a.receiverType){case window.chrome.cast.ReceiverType.CUSTOM:D7(this,
new z7(this.o,a));break;case window.chrome.cast.ReceiverType.DIAL:D7(this,new y7(this.o,a,this.D));break;case window.chrome.cast.ReceiverType.CAST:D7(this,new x7(this.o,a));break;default:this.Zb("Unknown receiver type: "+a.receiverType)}break;case window.chrome.cast.ReceiverAction.STOP:this.g&&this.g.o.label==a.label?this.g.stop():this.Zb("Stopping receiver w/o session: "+a.friendlyName)}else this.Zb("onReceiverAction_ called without receiver.")};
g.h.TO=function(a){if(this.ia())return window.Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=window.chrome.cast.ReceiverType.DIAL&&(this.Zb("Not DIAL receiver: "+b.friendlyName),b.receiverType=window.chrome.cast.ReceiverType.DIAL);var c=this.g?this.g.o:null;if(!c||c.label!=b.label)return this.Zb("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),window.Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=window.chrome.cast.ReceiverType.DIAL){if(this.g.A)return B7("Reselecting dial screen."),
this.T("yt-remote-cast2-session-change",this.g.A),window.Promise.resolve(new window.chrome.cast.DialLaunchResponse(!1));this.Zb('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);D7(this,new y7(this.o,b,this.D))}b=this.g;b.G=a;return b.G.appState==window.chrome.cast.DialAppState.RUNNING?new window.Promise((0,g.z)(b.vJ,b,(b.G.extraData||{}).screenId||null)):new window.Promise((0,g.z)(b.Nr,b))};
g.h.oB=function(a){if(!this.ia()){B7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=window.chrome.cast.ReceiverType.CUSTOM){if(!this.g)if(b.receiverType==window.chrome.cast.ReceiverType.CAST)B7("Got resumed cast session before resumed mdx connection."),b.friendlyName=window.chrome.cast.unescape(b.friendlyName),D7(this,new x7(this.o,b),!0);else{this.Zb("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.g.o,d=m6(this.o.fe(),c.label);
d&&h6(d,b.label)&&c.receiverType!=window.chrome.cast.ReceiverType.CAST&&b.receiverType==window.chrome.cast.ReceiverType.CAST&&(B7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.We(this.g),this.g=new x7(this.o,b),this.g.subscribe("sessionScreen",(0,g.z)(this.pB,this,this.g)),this.g.Dj(null));this.g.Wt(a)}}};
g.h.fU=function(){return this.g?this.g.rD():null};
g.h.iR=function(a){this.ia()||(this.Zb("Failed to estabilish a session: "+g.xg(a)),a.code!=window.chrome.cast.ErrorCode.CANCEL&&D7(this,null))};
g.h.PQ=function(a){B7("Receiver availability updated: "+a);if(!this.ia()){var b=C7(this);this.C=a==window.chrome.cast.ReceiverAvailability.AVAILABLE;C7(this)!=b&&this.T("yt-remote-cast2-availability-change",C7(this))}};
g.h.qD=function(){this.ia()||(this.A=HAa(this),B7("Updating custom receivers: "+g.xg(this.A)),window.chrome.cast.setCustomReceivers(this.A,g.y,(0,g.z)(function(){this.Zb("Failed to set custom receivers.")},this)),this.T("yt-remote-cast2-availability-change",C7(this)))};
A7.prototype.setLaunchParams=A7.prototype.dT;A7.prototype.setConnectedScreenStatus=A7.prototype.cT;A7.prototype.stopSession=A7.prototype.gU;A7.prototype.getCastSession=A7.prototype.fU;A7.prototype.requestSession=A7.prototype.requestSession;A7.prototype.init=A7.prototype.init;A7.prototype.dispose=A7.prototype.dispose;var J7=[];O7.prototype.reset=function(a){this.listId="";this.index=-1;this.videoId="";P7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.g=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.o=a.trackData,this.Lf=a.hasPrevious,this.hasNext=a.hasNext,this.G=a.playerTime,this.F=a.playerTimeAt,this.C=a.seekableStart,this.A=a.seekableEnd,this.I=a.duration,this.J=a.loadedTime,this.B=a.liveIngestionTime,this.D=!(0,window.isNaN)(this.B))};
O7.prototype.jb=function(){return 1==this.g};
O7.prototype.getDuration=function(){return this.D?this.I+Q7(this):this.I};
O7.prototype.clone=function(){return new O7(U7(this))};g.A(W7,g.BF);g.h=W7.prototype;g.h.play=function(){1==this.g?(this.o?this.o.play(null,g.y,b8(this,"play")):a8(this,"play"),$7(this,1,S7(X7(this))),this.T("remotePlayerChange")):Y7(this,this.play)};
g.h.pause=function(){1==this.g?(this.o?this.o.pause(null,g.y,b8(this,"pause")):a8(this,"pause"),$7(this,2,S7(X7(this))),this.T("remotePlayerChange")):Y7(this,this.pause)};
g.h.mD=function(a){if(1==this.g){if(this.o){var b=X7(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=b.jb()||3==b.g?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.o.seek(c,g.y,b8(this,"seekTo",{newTime:a}))}else a8(this,"seekTo",{newTime:a});$7(this,3,a);this.T("remotePlayerChange")}else Y7(this,g.Da(this.mD,a))};
g.h.stop=function(){if(1==this.g){this.o?this.o.stop(null,g.y,b8(this,"stopVideo")):a8(this,"stopVideo");var a=X7(this);a.index=-1;a.videoId="";P7(a);Z7(this,a);this.T("remotePlayerChange")}else Y7(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=X7(this);if(this.A){if(c.volume!=a){var d=Math.round(a)/100;this.A.setReceiverVolumeLevel(d,(0,g.z)(function(){f7("CP","set receiver volume: "+d)},this),(0,g.z)(function(){this.Zb("failed to set receiver volume.")},this))}c.muted!=b&&this.A.setReceiverMuted(b,(0,g.z)(function(){f7("CP","set receiver muted: "+b)},this),(0,g.z)(function(){this.Zb("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);a8(this,"setVolume",e)}c.muted=b;c.volume=a;Z7(this,c)}else Y7(this,g.Da(this.setVolume,a,b))};
g.h.tC=function(a,b){if(1==this.g){var c=X7(this),d={videoId:a};b&&(c.o={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.xg(b.style),g.ec(d,c.o));a8(this,"setSubtitlesTrack",d);Z7(this,c)}else Y7(this,g.Da(this.tC,a,b))};
g.h.Lu=function(a,b){if(1==this.g){a8(this,"setAudioTrack",{videoId:a,audioTrackId:b.Rc.id});var c=X7(this);c.audioTrackId=b.Rc.id;Z7(this,c)}else Y7(this,g.Da(this.Lu,a,b))};
g.h.lD=function(a,b){if(1==this.g){if(a&&b){var c=X7(this);T7(c,a,b);Z7(this,c)}a8(this,"previous")}else Y7(this,g.Da(this.lD,a,b))};
g.h.kD=function(a,b){if(1==this.g){if(a&&b){var c=X7(this);T7(c,a,b);Z7(this,c)}a8(this,"next")}else Y7(this,g.Da(this.kD,a,b))};
g.h.Lw=function(){1==this.g?a8(this,"dismissAutoplay"):Y7(this,this.Lw)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.T("proxyStateChange",a,this.g)}W7.Y.dispose.call(this)};
g.h.W=function(){TAa(this);this.B=null;this.C.clear();V7(this,null);W7.Y.W.call(this)};
g.h.Mu=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.T("proxyStateChange",b,a);if(1==a)for(;!this.C.isEmpty();)g.oC(this.C).apply(this);else 3==a&&this.dispose()}};
g.h.HQ=function(a,b){this.T(a,b)};
g.h.pO=function(a){if(!a)this.Dl(null),V7(this,null);else if(this.A.receiver.volume){a=this.A.receiver.volume;var b=X7(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)f7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,Z7(this,b)}};
g.h.Dl=function(a){f7("CP","Cast media: "+!!a);this.o&&this.o.removeUpdateListener(this.G);if(this.o=a)this.o.addUpdateListener(this.G),UAa(this),this.T("remotePlayerChange")};
g.h.oO=function(a){a?(UAa(this),this.T("remotePlayerChange")):this.Dl(null)};
g.h.CO=function(){var a=QAa();a&&V7(this,a)};
g.h.Zb=function(a){f7("CP",a)};g.A(c8,g.BF);g.h=c8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime;g.u(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.u(k)&&(l.currentIndex=k);c&&(this.bb.listId=c);this.bb.videoId=d;this.bb.index=k||0;this.bb.state=3;R7(this.bb,m);this.B="UNSUPPORTED";d8("Connecting with setPlaylist and params: "+g.xg(l));this.g.connect({method:"setPlaylist",params:g.xg(l)},a,oza())}else d8("Connecting without params"),
this.g.connect({},a,oza());WAa(this)};
g.h.dispose=function(){this.ia()||(this.T("beforeDispose"),e8(this,3));c8.Y.dispose.call(this)};
g.h.W=function(){f8(this);h8(this);g8(this);g.ZD(this.I);this.I=window.NaN;g.ZD(this.J);this.J=window.NaN;this.A=null;g.nF(this.R);this.R.length=0;this.g.dispose();c8.Y.W.call(this);this.B=this.F=this.o=this.bb=this.g=null};
g.h.JH=function(){this.D(2)};
g.h.tO=function(){d8("Channel opened");this.O&&(this.O=!1,g8(this),this.N=g.XD((0,g.z)(function(){d8("Timing out waiting for a screen.");this.D(1)},this),15E3));
sza(gAa(this.g),this.Z)};
g.h.qO=function(){d8("Channel closed");(0,window.isNaN)(this.C)?r6(!0):r6();this.dispose()};
g.h.rO=function(a){r6();(0,window.isNaN)(this.G())?(d8("Channel error: "+a+" without reconnection"),this.dispose()):(this.O=!0,d8("Channel error: "+a+" with reconnection in "+this.G()+" ms"),e8(this,2))};
g.h.sO=function(a){a.params?d8("Received: action="+a.action+", params="+g.xg(a.params)):d8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=g.gx(a.params.devices);this.o=(0,g.H)(a,function(a){return new f6(a)});
a=!!g.fb(this.o,function(a){return"LOUNGE_SCREEN"==a.type});
ZAa(this,a);break;case "loungeScreenDisconnected":g.tb(this.o,function(a){return"LOUNGE_SCREEN"==a.type});
ZAa(this,!1);break;case "remoteConnected":var b=new f6(g.gx(a.params.device));g.fb(this.o,function(a){return b?a.id==b.id:!1})||g.qb(this.o,b);
break;case "remoteDisconnected":b=new f6(g.gx(a.params.device));g.tb(this.o,function(a){return b?a.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":aBa(this,a);break;case "nowPlaying":cBa(this,a);break;case "onStateChange":bBa(this,a);break;case "onAdStateChange":dBa(this,a);break;case "onVolumeChanged":eBa(this,a);break;case "onSubtitlesTrackChanged":$Aa(this,a);break;case "nowAutoplaying":fBa(this,a);break;case "autoplayDismissed":this.T("autoplayDismissed");break;case "autoplayUpNext":this.F=a.params.videoId||null;this.T("autoplayUpNext",this.F);break;case "onAutoplayModeChanged":this.B=
a.params.autoplayMode;this.T("autoplayModeChange",this.B);"DISABLED"==this.B&&this.T("autoplayDismissed");break;case "onHasPreviousNextChanged":gBa(this,a);break;case "requestAssistedSignIn":this.T("assistedSignInRequested",a.params.authCode);break;default:d8("Unrecognized action: "+a.action)}};
g.h.NS=function(){if(this.A){var a=this.A;this.A=null;this.bb.videoId!=a&&i8(this,"getNowPlaying")}};
c8.prototype.subscribe=c8.prototype.subscribe;c8.prototype.unsubscribeByKey=c8.prototype.Hd;c8.prototype.ea=function(){var a=3;this.ia()||(a=0,(0,window.isNaN)(this.G())?a7(this.g)&&(0,window.isNaN)(this.C)&&(a=1):a=2);return a};
c8.prototype.getProxyState=c8.prototype.ea;c8.prototype.D=function(a){d8("Disconnecting with "+a);f8(this);this.T("beforeDisconnect",a);1==a&&r6();hAa(this.g,a);this.dispose()};
c8.prototype.disconnect=c8.prototype.D;c8.prototype.da=function(){var a=this.bb;this.A&&(a=this.bb.clone(),T7(a,this.A,a.index));return U7(a)};
c8.prototype.getPlayerContextData=c8.prototype.da;
c8.prototype.la=function(a){var b=new O7(a);b.videoId&&b.videoId!=this.bb.videoId&&(this.A=b.videoId,g.ZD(this.I),this.I=g.XD((0,g.z)(this.NS,this),5E3));var c=[];this.bb.listId==b.listId&&this.bb.videoId==b.videoId&&this.bb.index==b.index||c.push("remoteQueueChange");this.bb.g==b.g&&this.bb.volume==b.volume&&this.bb.muted==b.muted&&S7(this.bb)==S7(b)&&g.xg(this.bb.o)==g.xg(b.o)||c.push("remotePlayerChange");this.bb.reset(a);(0,g.G)(c,function(a){this.T(a)},this)};
c8.prototype.setPlayerContextData=c8.prototype.la;c8.prototype.X=function(){var a=this.g.D.id,b=g.fb(this.o,function(b){return"REMOTE_CONTROL"==b.type&&b.id!=a});
return b?b.id:""};
c8.prototype.getOtherConnectedRemoteId=c8.prototype.X;c8.prototype.G=function(){var a=this.g;return a.o.isActive()?a.o.o-(0,g.F)():window.NaN};
c8.prototype.getReconnectTimeout=c8.prototype.G;c8.prototype.aa=function(){return this.B||"UNSUPPORTED"};
c8.prototype.getAutoplayMode=c8.prototype.aa;c8.prototype.ca=function(){return this.F||""};
c8.prototype.getAutoplayVideoId=c8.prototype.ca;c8.prototype.pa=function(){if(!(0,window.isNaN)(this.G())){var a=this.g.o;g.$t(a.g);a.start()}};
c8.prototype.reconnect=c8.prototype.pa;c8.prototype.ga=function(a,b){i8(this,a,b);YAa(this)};
c8.prototype.sendMessage=c8.prototype.ga;g.A(j8,j7);g.h=j8.prototype;g.h.fe=function(a){return this.dd.$_gs(a)};
g.h.contains=function(a){return!!this.dd.$_c(a)};
g.h.get=function(a){return this.dd.$_g(a)};
g.h.start=function(){this.dd.$_st()};
g.h.add=function(a,b,c){this.dd.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.dd.$_r(a,b,c)};
g.h.np=function(a,b,c,d){this.dd.$_un(a,b,c,d)};
g.h.W=function(){for(var a=0,b=this.o.length;a<b;++a)this.dd.$_ubk(this.o[a]);this.o.length=0;this.dd=null;j8.Y.W.call(this)};
g.h.cU=function(){this.T("screenChange")};
g.h.nQ=function(){this.T("onlineScreenChange")};
s7.prototype.$_st=s7.prototype.start;s7.prototype.$_gspc=s7.prototype.dU;s7.prototype.$_gsppc=s7.prototype.pD;s7.prototype.$_c=s7.prototype.contains;s7.prototype.$_g=s7.prototype.get;s7.prototype.$_a=s7.prototype.add;s7.prototype.$_un=s7.prototype.np;s7.prototype.$_r=s7.prototype.remove;s7.prototype.$_gs=s7.prototype.fe;s7.prototype.$_gos=s7.prototype.oD;s7.prototype.$_s=s7.prototype.subscribe;s7.prototype.$_ubk=s7.prototype.Hd;var k8=null,l8=null,e9=null,p8=[];g.p(f9,g.L);g.h=f9.prototype;
g.h.W=function(){g.L.prototype.W.call(this);this.B.stop();this.C.stop();this.L.stop();this.O();this.g.unsubscribe("proxyStateChange",this.mB,this);this.g.unsubscribe("remotePlayerChange",this.Fl,this);this.g.unsubscribe("remoteQueueChange",this.Co,this);this.g.unsubscribe("autoplayUpNext",this.LA,this);this.g.unsubscribe("previousNextChange",this.jB,this);this.g.unsubscribe("nowAutoplaying",this.bB,this);this.g.unsubscribe("autoplayDismissed",this.KA,this);this.g=this.G=null};
g.h.vz=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(i9(this)){if(1081!=X7(this.g).g||"control_seek"!=a)switch(a){case "control_toggle_play_pause":X7(this.g).jb()?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.J.mj(c[0],c[1]);break;case "control_subtitles_set_track":j9(this,c[0]);break;case "control_set_audio_track":c=c[0],i9(this)&&this.g.Lu(this.o.fa(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.o.getCurrentTime();k9(this,0==c?void 0:c);break;case "control_seek":k9(this,c[0]);break;case "control_subtitles_set_track":j9(this,c[0]);break;case "control_set_audio_track":c=c[0],i9(this)&&this.g.Lu(this.o.fa(1).videoId,c)}};
g.h.nO=function(a){this.L.FH(a)};
g.h.CT=function(a){this.vz("control_subtitles_set_track",g.Yb(a)?null:a)};
g.h.FC=function(){var a=this.o.xc("captions","track");g.Yb(a)||j9(this,a)};
g.h.ZA=function(a){if(i9(this)){this.g.unsubscribe("remotePlayerChange",this.Fl,this);var b=Math.round(a.volume);a=!!a.muted;var c=X7(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.N.start();this.g.subscribe("remotePlayerChange",this.Fl,this)}};
g.h.GP=function(){g.Yb(this.D)||sBa(this,this.D);this.F=!1};
g.h.mB=function(a,b){this.C.stop();2==b&&this.CC()};
g.h.Fl=function(){if(i9(this)){this.B.stop();var a=X7(this.g);switch(a.g){case 1081:case 1:h9(this,new g.kO(8));this.BC();break;case 1085:case 3:h9(this,new g.kO(9));break;case 1083:case 0:h9(this,new g.kO(2));this.J.stop();g9(this,this.o.fa().lengthSeconds);break;case 1084:h9(this,new g.kO(4));break;case 2:h9(this,new g.kO(4));g9(this,S7(a));break;case -1:h9(this,new g.kO(64));break;case -1E3:a={errorCode:"mdx.remoteerror",message:g.T("YTP_MDX_PLAYER_ERROR")},h9(this,new g.kO(128,a))}a=X7(this.g).o;
var b=this.D;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.D=a,sBa(this,a));a=X7(this.g);-1==a.volume||Math.round(this.o.getVolume())==a.volume&&this.o.isMuted()==a.muted||this.N.isActive()||this.dD()}else rBa(this)};
g.h.jB=function(){this.o.T("mdxpreviousnextchange")};
g.h.Co=function(){i9(this)||rBa(this)};
g.h.OG=function(){this.g.Lw()};
g.h.LA=function(a){a&&(a=g.mE("/watch_queue_ajax",{method:"GET",Zc:{action_get_watch_queue_item:1,video_id:a},Hb:(0,g.z)(this.HR,this)}))&&(this.O=(0,g.z)(a.abort,a))};
g.h.HR=function(a,b){var c=new g.mN({videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.o.T("mdxautoplayupnext",c)};
g.h.bB=function(a){(0,window.isNaN)(a)||this.o.T("mdxnowautoplaying",a)};
g.h.KA=function(){this.o.T("mdxautoplaycanceled")};
g.h.YK=function(a,b){-1==X7(this.g).g?k9(this,a):b&&this.g.mD(a)};
g.h.dD=function(){if(i9(this)){var a=X7(this.g);this.A.Ea(this.R);a.muted?this.o.mute():this.o.Yf();this.o.setVolume(a.volume);this.R=this.A.P(this.o,"onVolumeChange",this.ZA)}};
g.h.BC=function(){this.B.stop();if(!this.g.ia()){var a=X7(this.g);a.jb()&&h9(this,new g.kO(8));g9(this,S7(a));this.B.start()}};
g.h.CC=function(){this.C.stop();this.B.stop();var a=this.g.B.getReconnectTimeout();2==this.g.g&&!(0,window.isNaN)(a)&&this.C.start()};g.p(l9,g.Y);l9.prototype.B=function(a){uBa(this,a.state)};g.p(m9,g.e_);m9.prototype.J=function(){var a=this.o.xc("remote","receivers");a&&1<a.length&&!this.o.xc("remote","quickCast")?(this.G=g.Hb(a,this.C,this),g.f_(this,(0,g.H)(a,this.C)),a=this.o.xc("remote","currentReceiver"),this.qf(this.C(a)),this.enable(!0)):this.enable(!1)};
m9.prototype.C=function(a){return a.key};
m9.prototype.pf=function(a){return"cast-selector-receiver"==a?g.T("YTP_MDX_CAST_SELECTOR"):this.G[a].name};
m9.prototype.sd=function(a){g.e_.prototype.sd.call(this,a);this.o.Fd("remote","currentReceiver",this.G[a]);this.B.Mb()};g.p(n9,g.LU);g.h=n9.prototype;g.h.create=function(){lBa(g.HL(g.X(this.g)));this.D.push(g.OF("yt-remote-before-disconnect",this.jO,this));this.D.push(g.OF("yt-remote-connection-change",this.QQ,this));this.D.push(g.OF("yt-remote-receiver-availability-change",this.kB,this));this.D.push(g.OF("yt-remote-auto-connect",this.OQ,this));this.D.push(g.OF("yt-remote-receiver-resumed",this.NQ,this));this.kB()};
g.h.load=function(){this.g.Os();g.LU.prototype.load.call(this);this.C=new f9(this,this.g,this.o);var a=(a=qBa())?a.currentTime:0;var b=d9()?new W7(u8(),void 0):null;0==a&&b&&(a=S7(X7(b)));0!=a&&(this.I=a||0,this.g.T("progresssync",a,void 0));tBa(this,this.F,this.F);g.a0(this.g.app,6)};
g.h.unload=function(){this.g.T("mdxautoplaycanceled");this.B=this.A;g.Xe(this.C,this.o);this.o=this.C=null;g.LU.prototype.unload.call(this);g.a0(this.g.app,5)};
g.h.W=function(){g.PF(this.D);g.LU.prototype.W.call(this)};
g.h.ol=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.C.vz.apply(this.C,[].concat([a],g.pa(c)))};
g.h.BH=function(){return this.loaded?this.C.suggestion:null};
g.h.Lf=function(){return this.o?X7(this.o).Lf:!1};
g.h.hasNext=function(){return this.o?X7(this.o).hasNext:!1};
g.h.getCurrentTime=function(){return this.I};
g.h.BK=function(){var a=X7(this.o),b=this.g.fa();return{allowSeeking:this.g.ed(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.D?a.B+Q7(a):a.B,isPeggedToLive:1>=(a.D?a.A+Q7(a):a.A)-this.getCurrentTime(),loaded:a.J,seekableEnd:a.D?a.A+Q7(a):a.A,seekableStart:0<a.C?a.C+Q7(a):a.C}};
g.h.CK=function(){this.o&&this.o.kD()};
g.h.DK=function(){this.o&&this.o.lD()};
g.h.jO=function(a){1==a&&(this.J=this.o?X7(this.o):null)};
g.h.QQ=function(){var a=d9()?new W7(u8(),void 0):null;if(a){var b=this.B;this.loaded&&this.unload();this.o=a;this.J=null;b.key!=this.A.key&&(this.B=b,this.load())}else g.We(this.o),this.o=null,this.loaded&&(this.unload(),(a=this.J)&&a.videoId==this.g.fa().videoId&&this.g.Cz(a.videoId,S7(a)));this.g.T("videodatachange","newdata",this.g.fa(),3)};
g.h.kB=function(){this.G=[this.A].concat(nBa());var a=v8()||this.A;o9(this,a);this.g.ua("onMdxReceiversChange")};
g.h.OQ=function(){var a=v8();o9(this,a)};
g.h.NQ=function(){this.B=v8()};
g.h.AK=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.G;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?M7():o9(this,b)),this.loaded?this.B:this.A;case "quickCast":return 2==this.G.length&&"cast-selector-receiver"==this.G[1].key?(b&&M7(),!0):!1}};
g.h.EK=function(){a8(this.o,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.hd=function(){return!1};g.gY.remote=n9;})(_yt_player);
