//tealium universal tag - utag.104 ut4.0.201608221843, Copyright 2016 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader){var u={};utag.o[loader].sender[id]=u;if(utag.ut===undefined){utag.ut={};}
if(utag.ut.loader===undefined){u.loader=function(o){var b,c,l,a=document;if(o.type==="iframe"){b=a.createElement("iframe");o.attrs=o.attrs||{"height":"1","width":"1","style":"display:none"};for(l in utag.loader.GV(o.attrs)){b.setAttribute(l,o.attrs[l]);}b.setAttribute("src",o.src);}else if(o.type=="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";for(l in utag.loader.GV(o.attrs)){b[l]=o.attrs[l];}b.src=o.src;}if(o.id){b.id=o.id};if(typeof o.cb=="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb()},false);}else{b.onreadystatechange=function(){if(this.readyState=='complete'||this.readyState=='loaded'){this.onreadystatechange=null;o.cb()}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l=="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b)}}}}else{u.loader=utag.ut.loader;}
if(utag.ut.typeOf===undefined){u.typeOf=function(e){return({}).toString.call(e).match(/\s([a-zA-Z]+)/)[1].toLowerCase();};}else{u.typeOf=utag.ut.typeOf;}
u.ev={"view":1};u.map={"bouncex_id":"client_id"};u.extend=[function(a,b,c,d,e,f,g){d=b['dom.domain'];if(typeof d=='undefined')return;c=[{'allyou.com':'1487'},{'coastalliving.com':'1493'},{'cookinglight.com':'1492'},{'ew.com':'1494'},{'essence.com':'1495'},{'foodandwine.com':'1368'},{'fortune.com':'1496'},{'golf.com':'1497'},{'health.com':'1498'},{'instyle.com':'1376'},{'myhomeideas.com':'1499'},{'myrecipes.com':'1500'},{'people.com':'1373'},{'peoplestylewatch.com':'1501'},{'realsimple.com':'1367'},{'southernliving.com':'1502'},{'si.com':'1375'},{'sunset.com':'1503'},{'thisoldhouse.com':'1506'},{'time.com':'1709'},{'travelandleisure.com':'1505'},{'dailycut.com':'1508'},{'theoutfit.com':'1504'},{'thesnug.com':'1507'},{'motto.time.com':'1824'}];var m=false;for(e=0;e<c.length;e++){for(f in c[e]){if(d.toString().indexOf(f)>-1){b['bouncex_id']=c[e][f];m=true};};if(m)break};if(!m)b['bouncex_id']='1374';},function(a,b){if(!b.bouncex_id){return false;}
u.data.client_id=b.bouncex_id}];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f;u.data={"base_url":"//tag.bounceexchange.com/##utag_website_id##/i.js","website_id":""};for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){if(typeof utag_err!='undefined'){utag_err.push({e:'extension error:'+e,s:utag.cfg.path+'utag.'+id+'.js',l:c,t:'ex'})}}};for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}}
u.data.website_id=u.data.website_id||u.data.client_id||"";u.data.order_id=u.data.order_id||b._corder||"";u.data.order_subtotal=u.data.amount||b._csubtotal||"";u.data.customer_id=u.data.email||b._ccustid||"";if(u.data.order_id){window.bxAsyncInit=function(){var conversion_data={};conversion_data.order_id=u.data.order_id;conversion_data.amount=u.data.order_subtotal;conversion_data.email=u.data.customer_id;if(u.data.goal){conversion_data.goal=u.data.goal;}
bouncex.report_conversion(conversion_data);};}
u.data.base_url=u.data.base_url.replace("##utag_website_id##",u.data.website_id);u.loader({"type":"script","src":u.data.base_url,"cb":null,"loc":"script","id":"utag_104"});}};utag.o[loader].loader.LOAD(id);}("104","timeinc.health.com"));}catch(error){utag.DB(error);}
